lsclsj2000/outpolic

- outpolic/src/main/java/outpolic/common/domain/member.java
- outpolic/src/main/java/outpolic/user/login/controller/userLoginController.java
- outpolic/src/main/java/outpolic/user/mypage/controller/userMypageController.java
- outpolic/src/main/java/outpolic/user/mypage/dto/mypageDTO.java
- outpolic/src/main/java/outpolic/user/mypage/dto/userInfoDTO.java
- outpolic/src/main/java/outpolic/user/mypage/dto/userOsInfoDTO.java
- outpolic/src/main/java/outpolic/user/mypage/mapper/UserMypageEditMapper.java
- outpolic/src/main/java/outpolic/user/mypage/service/Impl/UserMypageEditServiceImpl.java
- outpolic/src/main/java/outpolic/user/mypage/service/UserMypageEditService.java
- outpolic/src/main/resources/mapper/mypageEdit/UserMypageMapper.xml
- outpolic/src/main/resources/templates/user/fragments/userHeader.html
- outpolic/src/main/resources/templates/user/mypage/userMypageView.html
detail : 마이페이지 관련 dto 추가 및 전체적인 도메인과 dto 수정작업을 진행함.
> [outpolic-SSY] 마이페이지 구조 수정

- outpolic/src/main/resources/templates/user/fragments/userHeader.html
detail : fragments에서 userHeader 검색기능 변경
> [outpolic-KHB] 검색기능 변경

- outpolic/src/main/java/outpolic/user/login/controller/UserLoginController.java
- outpolic/src/main/java/outpolic/user/mypage/controller/UserMypageController.java
- outpolic/src/main/java/outpolic/user/mypage/dto/MypageDTO.java
- outpolic/src/main/java/outpolic/user/mypage/dto/UserInfoDTO.java
- outpolic/src/main/java/outpolic/user/mypage/dto/UserOsInfoDTO.java
- outpolic/src/main/java/outpolic/user/mypage/mapper/UserMypageEditMapper.java
- outpolic/src/main/java/outpolic/user/mypage/service/Impl/UserMypageEditServiceImpl.java
- outpolic/src/main/java/outpolic/user/mypage/service/UserMypageEditService.java
- outpolic/src/main/java/outpolic/user/register/controller/UserRegisterController.java
- outpolic/src/main/resources/templates/user/layout/userMypageLayout.html
detail : th문법으로 css 적용 안되는 html(userLayoutMain) 절대경로로 묶음
> [outpolic-KHB] view파일 수정

- outpolic/src/main/java/outpolic/user/goods/controller/userGoodsController.java
- outpolic/src/main/resources/static/user/assets/css/main.css
- outpolic/src/main/resources/templates/user/goods/userGoodsList.html
detail : user->goods패키지 생성 및 userGoodsList.html, main.css 수정
> [outpolic-LSJ] 패키지 생성 및 html, css 수정

- outpolic/src/main/resources/log4jdbc.log4j2.properties
- outpolic/src/main/resources/logback-spring.xml
- outpolic/src/main/resources/mapper/user/search/searchMapper.xml
- outpolic/src/main/resources/templates/user/contentsParticular/userContentsParticularView.html
- outpolic/src/main/resources/templates/user/layout/userLayoutMain.html
- outpolic/src/main/resources/templates/user/search/userSearchView.html
> [outpolic-KHB] 쿼리 나오는 설정

- outpolic/pom.xml
> [outpolic-SSY] pom수정

- outpolic/pom.xml
- outpolic/src/main/resources/templates/user/search/userSearchView.html
> [outpolic-KHB] 가독성 패치

- outpolic/src/main/java/outpolic/user/inquiry/config/WebConfig.java
- outpolic/src/main/resources/static/user/assets/css/main.css
- outpolic/src/main/resources/templates/user/inquiry/userInquiryDetailView.html
detail : 이부분은 추후 선생님 파일로 대체될 것 같은데, 최신 버전으로 다른 워크스페이스에서 테스트하고 다시 가져오겠습니다.
> [outpolic-YSR] 파일 기능 수정

- outpolic/src/main/java/outpolic/user/contents/controller/UserContentsController.java
- outpolic/src/main/java/outpolic/user/search/domain/ContentsDetailDTO.java
- outpolic/src/main/java/outpolic/user/search/mapper/SearchMapper.java
- outpolic/src/main/java/outpolic/user/search/service/SearchService.java
- outpolic/src/main/java/outpolic/user/search/service/impl/SearchServiceImpl.java
- outpolic/src/main/resources/mapper/user/search/searchMapper.xml
- outpolic/src/main/resources/static/user/assets/css/main.css
- outpolic/src/main/resources/templates/user/contentsParticular/userContentsParticularView.html
- outpolic/src/main/resources/templates/user/fragments/userHeader.html
- outpolic/src/main/resources/templates/user/search/userSearchView.html
detail : 콘텐츠 상세 페이지 작성 및 헤더의 로고부분 클릭시 홈으로 링크 걸어둠
> [outpolic-KHB] 콘텐츠 상세 페이지 생성

- outpolic/src/main/java/outpolic/user/payment/controller/UserPaymentController.java
- outpolic/src/main/java/outpolic/user/payment/dto/SettlementDTO.java
- outpolic/src/main/resources/mapper/user/payment/UserPaymentMapper.xml
detail : DTO추가 및 수정, HTML JS 수정, Controller 수정
> [outpolic-LSJ] DTO, HTML, Controller

- outpolic/src/main/java/outpolic/user/category/controller/CategoryController.java
- outpolic/src/main/java/outpolic/user/category/domain/SubCategory.java
- outpolic/src/main/java/outpolic/user/category/mapper/CategoryMapper.java
- outpolic/src/main/java/outpolic/user/category/service/CategoryService.java
- outpolic/src/main/java/outpolic/user/category/service/impl/CategoryServiceImpl.java
- outpolic/src/main/java/outpolic/user/contents/controller/UserContentsController.java
- outpolic/src/main/java/outpolic/user/main/controller/UserHomeController.java
- outpolic/src/main/java/outpolic/user/search/domain/ContentsDetailDTO.java
- outpolic/src/main/resources/mapper/user/category/categoryMapper.xml
- outpolic/src/main/resources/mapper/user/search/searchMapper.xml
- outpolic/src/main/resources/static/user/assets/css/main.css
- outpolic/src/main/resources/templates/main.html
- outpolic/src/main/resources/templates/user/contents/userContentsView.html
- outpolic/src/main/resources/templates/user/contentsParticular/userContentsParticularView.html
- outpolic/src/main/resources/templates/user/fragments/userCategorySidebar.html
- outpolic/src/main/resources/templates/user/layout/userLayoutListpage.html
detail : 카테고리 정보를 가져오기까진 했는데 아직 디테일 페이지로 이동하기는 내일의 나에게 맡기도록 할게요 ㅎㅇㅌ
> [outpolic-KHB] 카테고리 완성 및 상세페이지 오류 해결

- outpolic/src/main/java/outpolic/user/category/controller/CategoryController.java
- outpolic/src/main/java/outpolic/user/category/mapper/CategoryMapper.java
- outpolic/src/main/java/outpolic/user/category/service/CategoryService.java
- outpolic/src/main/java/outpolic/user/category/service/impl/CategoryServiceImpl.java
- outpolic/src/main/java/outpolic/user/contents/controller/UserContentsController.java
- outpolic/src/main/java/outpolic/user/search/domain/ContentItemDTO.java
- outpolic/src/main/java/outpolic/user/search/mapper/SearchMapper.java
- outpolic/src/main/java/outpolic/user/search/service/SearchService.java
- outpolic/src/main/java/outpolic/user/search/service/impl/SearchServiceImpl.java
- outpolic/src/main/resources/mapper/user/search/searchMapper.xml
- outpolic/src/main/resources/templates/user/contents/userContentsView.html
> [outpolic-KHB] 카테고리작업중

- outpolic/src/main/java/outpolic/admin/inquiry/domain/AdminInquiry.java
- outpolic/src/main/java/outpolic/admin/inquiry/domain/AdminInquiryFile.java
- outpolic/src/main/java/outpolic/admin/inquiry/domain/AdminInquiryProcess.java
- outpolic/src/main/java/outpolic/admin/inquiry/domain/AdminInquiryType.java
- outpolic/src/main/java/outpolic/admin/inquiry/mapper/AdminInquiryMapper.java
- outpolic/src/main/resources/mapper/admin/inquiry/AdminInquiryMapper.xml
- outpolic/src/main/resources/static/user/assets/css/main.css
- outpolic/src/main/resources/templates/admin/inquiry/adminInquiryView.html
- outpolic/src/main/resources/templates/user/inquiry/userInquiryDetailView.html
- outpolic/src/main/resources/templates/user/inquiry/userInquiryListView.html
detail : 관리자 문의 페이지 뷰, 컨트롤러, DTO 추가
> [outpolic-YSR] admin inquiry 패키지 생성

- outpolic/src/main/java/outpolic/admin/inquiry/controller/AdminInquiryController.java
- outpolic/src/main/java/outpolic/admin/inquiry/domain/AdminInquiry.java
- outpolic/src/main/java/outpolic/admin/inquiry/service/AdminInquiryService.java
- outpolic/src/main/java/outpolic/admin/inquiry/service/Impl/AdminInquiryServiceImpl.java
- outpolic/src/main/resources/mapper/admin/inquiry/AdminInquiryMapper.xml
- outpolic/src/main/resources/templates/admin/inquiry/adminInquiryView.html
detail : 관리자 페이지 문의 내역 구현하는 중이어요
> [outpolic-YSR] admin 문의 내역 페이지 구현

- outpolic/src/main/java/outpolic/enter/outsourcing/controller/EnterOutsourcingController.java
- outpolic/src/main/java/outpolic/enter/outsourcing/domain/EnterOutsourcing.java
- outpolic/src/main/java/outpolic/enter/outsourcing/mapper/OutsourcingMapper.java
- outpolic/src/main/java/outpolic/enter/outsourcing/service/EnterOutsourcingService.java
- outpolic/src/main/java/outpolic/enter/outsourcing/service/impl/EnterOutsourcingServiceImpl.java
- outpolic/src/main/java/outpolic/enter/portfolio/mapper/PortfolioMapper.java
- outpolic/src/main/resources/mapper/enter/Outsourcing/OutsourcingMapper.xml
- outpolic/src/main/resources/mapper/enter/Portfolio/PortfolioMapper.xml
- outpolic/src/main/resources/static/enter/assets/css/main.css
- outpolic/src/main/resources/templates/enter/outsourcing/addOutsourcingListView.html
- outpolic/src/main/resources/templates/enter/outsourcing/outsourcingListView.html
- outpolic/src/main/resources/templates/enter/portfolio/portfolioListView.html
> [outpolic-KJW]

- outpolic/src/main/resources/static/admin/assets/css/main.css
- outpolic/src/main/resources/templates/admin/fragments/adminAside.html
- outpolic/src/main/resources/templates/admin/inquiry/adminInquiryView.html
detail : 관리자 문의 내역 수정과 관련한 팝업창과 css 추가가 있읍니다
> [outpolic-YSR] 관리자 문의 내역 수정

- outpolic/src/main/java/outpolic/admin/inquiry/controller/AdminInquiryController.java
- outpolic/src/main/java/outpolic/admin/inquiry/domain/AdminInquiry.java
- outpolic/src/main/java/outpolic/admin/inquiry/mapper/AdminInquiryMapper.java
- outpolic/src/main/java/outpolic/admin/inquiry/service/AdminInquiryService.java
- outpolic/src/main/java/outpolic/admin/inquiry/service/Impl/AdminInquiryServiceImpl.java
- outpolic/src/main/resources/mapper/admin/inquiry/AdminInquiryMapper.xml
- outpolic/src/main/resources/static/admin/assets/css/main.css
- outpolic/src/main/resources/templates/admin/inquiry/adminInquiryView.html
> [outpolic-YSR] 문의 팝업창 수정

- outpolic/src/main/resources/templates/admin/inquiry/adminInquiryView.html
> [outpolic-YSR] 문의 수정

- outpolic/src/main/java/outpolic/user/login/controller/UserLoginController.java
- outpolic/src/main/java/outpolic/user/login/service/Impl/UserLoginServiceImpl.java
- outpolic/src/main/java/outpolic/user/login/service/UserLoginService.java
- outpolic/src/main/resources/static/user/assets/js/userService.js
- outpolic/src/main/resources/templates/user/login/userLoginView.html
> [outpolic-SSY] 회원가입 기능 구현중

- outpolic/src/main/java/outpolic/user/login/controller/UserLoginController.java
- outpolic/src/main/java/outpolic/user/login/interceptor/LoginInterceptor.java
- outpolic/src/main/java/outpolic/user/mypage/controller/UserMypageController.java
- outpolic/src/main/resources/mapper/user/login/UserLoginMapper.xml
[상세 내용] 회원가입은 기능적으로 완성했고, 쿠키에 저장되는것도 확인. 하지만 마이페이지에 하드코딩해둔 id와 회원가입하려고 pw 암호화 풀어둔 id가 같은거여서 하드코딩해뒀던 내용을 다 삭제했는지 여부를 알 수 없어서 내일 db 확인하고 마저 하려함. 아직 interceptor는 적용안함. 팀원들에게 각각 interceptor 적용 범위 제공받아서 추가할 예정. 내일 로그인 기록 테이블에 로그인시 데이터 insert 되도록 처리할 예정.
> [outpolic-SSY] 회원가입 기능 완성

- outpolic/src/main/resources/static/admin/assets/css/main.css
- outpolic/src/main/resources/templates/admin/inquiry/adminInquiryView.html
> [outpolic-YSR] 관리자 문의창

- outpolic/pom.xml
- outpolic/src/main/java/outpolic/systems/config/WebConfig.java
- outpolic/src/main/java/outpolic/user/login/interceptor/LoginInterceptor.java
> [outpolic-SSY] 인터셉터 적용

- outpolic/pom.xml
> [outpolic-LSJ] pom.xml 수정

- outpolic/src/main/resources/static/user/assets/css/userOutsourcingStatus.css
- outpolic/src/main/resources/templates/user/fragments/userHeader.html
- outpolic/src/main/resources/templates/user/osst/userOutsourcingStatus.html
- outpolic/src/main/resources/templates/user/osst/userOutsourcingStatusList.html
detail : 진행 중인 외주 목록 뷰와 외주 진행 현황 뷰를 만졌구용 ~ css도 만졌고 ~ header 프레그먼트에 주소도 연결했시요 ~
> [outpolic-YSR] 외주 뷰

- outpolic/src/main/resources/templates/main.html
detail : 외주 / 포트폴리오 컨텐츠 영역 생성 및 수정 했습니다.
> [outpolic-LSJ] 메인화면 수정

- outpolic/src/main/resources/templates/main.html
detail : 리뷰 슬라이드 자동변환 기능 추가했습니다. 상세 디자인은 추후에 수정하겠습니다
> [outpolic-LSJ] 주요기능

- outpolic/src/main/resources/static/user/assets/css/main.css
- outpolic/src/main/resources/static/user/assets/css/userInquiry.css
- outpolic/src/main/resources/templates/user/declaration/userDeclarationWriteView.html
- outpolic/src/main/resources/templates/user/layout/userLayoutMain.html
detail : 사용자의 신고 작성 페이지 수정 했습니당
> [outpolic-YSR] 신고 작성

- outpolic/src/main/resources/static/user/assets/css/main.css
- outpolic/src/main/resources/templates/user/declaration/userDeclarationWriteView.html
- outpolic/src/main/resources/templates/user/fragments/userHeader.html
> [outpolic-YSR] 사용자 신고 페이지

- outpolic/src/main/resources/static/user/assets/css/userChatRoom.css
- outpolic/src/main/resources/templates/admin/chat/adminChatRoomView.html
- outpolic/src/main/resources/templates/user/declaration/userDeclarationWriteView.html
- outpolic/src/main/resources/templates/user/fragments/userChatRoom.html
- outpolic/src/main/resources/templates/user/layout/userEditLayout.html
- outpolic/src/main/resources/templates/user/layout/userLayoutContentsParticular.html
- outpolic/src/main/resources/templates/user/layout/userLayoutInquiryDetail.html
- outpolic/src/main/resources/templates/user/layout/userLayoutInquiryList.html
- outpolic/src/main/resources/templates/user/layout/userLayoutInquiryWrite.html
- outpolic/src/main/resources/templates/user/layout/userLayoutListpage.html
- outpolic/src/main/resources/templates/user/layout/userLayoutMain.html
- outpolic/src/main/resources/templates/user/layout/userMypageLayout.html
detail : 모든 페이지에 채팅 아이콘을 추가하기 위해서 프레그먼트로 만들고, 모든 레이아웃에 프레그먼트 + link 추가했습니다
> [outpolic-YSR] 채팅 아이콘 추가

- outpolic/src/main/resources/mapper/user/ranking/UserRankingMapper.xml
- outpolic/src/main/resources/static/user/assets/css/userRanking.css
- outpolic/src/main/resources/static/user/assets/js/userRanking.js
- outpolic/src/main/resources/templates/main.html
- outpolic/src/main/resources/templates/user/chat/userChatRoomView.html
- outpolic/src/main/resources/templates/user/fragments/userChatRoom.html
- outpolic/src/main/resources/templates/user/layout/userLayoutMain.html
> [outpolic-KHB] 메인페이지 및 유저레이아웃 메인 수정 도중 백업

- outpolic/src/main/java/outpolic/enter/mypage/controller/enterMypageController.java
- outpolic/src/main/java/outpolic/enter/mypage/mapper/EnterMypageMapper.java
- outpolic/src/main/java/outpolic/enter/mypage/service/EnterMypageService.java
- outpolic/src/main/java/outpolic/enter/mypage/service/Impl/EnterMypageServiceImpl.java
- outpolic/src/main/java/outpolic/user/login/controller/UserLoginController.java
- outpolic/src/main/java/outpolic/user/mypage/controller/UserMypageController.java
- outpolic/src/main/java/outpolic/user/mypage/dto/MypageDTO.java
- outpolic/src/main/java/outpolic/user/mypage/dto/UserInfoDTO.java
- outpolic/src/main/java/outpolic/user/mypage/mapper/UserMypageEditMapper.java
- outpolic/src/main/java/outpolic/user/mypage/service/Impl/UserMypageEditServiceImpl.java
- outpolic/src/main/java/outpolic/user/mypage/service/UserMypageEditService.java
- outpolic/src/main/resources/mapper/enter/mypage/EnterMypageMapper.xml
- outpolic/src/main/resources/mapper/user/login/UserLoginMapper.xml
- outpolic/src/main/resources/mapper/user/mypageEdit/UserMypageMapper.xml
- outpolic/src/main/resources/static/enter/assets/js/enterService.js
- outpolic/src/main/resources/static/enter/assets/js/enterServiceAjax.js
- outpolic/src/main/resources/static/user/assets/js/userService.js
- outpolic/src/main/resources/static/user/assets/js/userServiceAjax.js
- outpolic/src/main/resources/templates/enter/mypage/enterEnterpriseInfoEditView.html
- outpolic/src/main/resources/templates/user/mypage/userProfileEditView.html
detail : id에서 cd사용하게 바꾸었으니 세션에서 로그인한 회원 정보 가져올 때 SCD 사용해주시길 바랍니다. 이제 기업정보 수정 페이지 만질 예정
> [outpolic-SSY] 전체적으로 memberCode를 사용하게 수정.

- outpolic/src/main/java/outpolic/admin/declaration/controller/AdminDeclarationController.java
- outpolic/src/main/java/outpolic/admin/declaration/domain/AdminDeclaration.java
- outpolic/src/main/java/outpolic/admin/declaration/mapper/AdminDeclarationMapper.java
- outpolic/src/main/java/outpolic/admin/declaration/service/AdminDeclarationService.java
- outpolic/src/main/java/outpolic/admin/declaration/service/Impl/AdminDeclarationServiceImpl.java
- outpolic/src/main/java/outpolic/admin/osst/controller/AdminOsstController.java
- outpolic/src/main/java/outpolic/user/osst/controller/UserOsstController.java
- outpolic/src/main/resources/mapper/admin/declaration/AdminDeclarationMapper.xml
- outpolic/src/main/resources/templates/admin/declaration/adminDeclarationView.html
- outpolic/src/main/resources/templates/admin/osst/adminOutsourcingStatusView.html
- outpolic/src/main/resources/templates/user/fragments/userHeader.html
detail : 관리자 '외주 진행 현황 페이지', '신고 내역 목록 페이지', '신고 처리 모달창' 구현
> [outpolic-YSR] 중간 커밋

- outpolic/src/main/java/outpolic/user/ranking/controller/UserRankingContoller.java
- outpolic/src/main/resources/static/user/assets/css/main.css
- outpolic/src/main/resources/templates/main.html
- outpolic/src/main/resources/templates/user/contents/userContentsView.html
- outpolic/src/main/resources/templates/user/contentsParticular/userContentsParticularView.html
- outpolic/src/main/resources/templates/user/layout/userLayoutContentsParticular.html
- outpolic/src/main/resources/templates/user/search/userSearchView.html
> [outpolic-KHB] 중간커밋

- outpolic/src/main/java/outpolic/user/login/controller/UserLoginController.java
- outpolic/src/main/resources/mapper/user/login/UserLoginMapper.xml
- outpolic/src/main/resources/templates/enter/layout/enterEditLayout.html
detail : 기업회원 회원가입 만들기 위해 그 전에 한번 커밋함. 로그인 기능 테스트해보고싶은사람은 db에 평문 비밀번호 되어있는 것 가져와서 테스트해보십쇼
> [outpolic-SSY] 로그인 분기처리 완료

- outpolic/src/main/java/outpolic/user/contents/controller/UserContentsController.java
- outpolic/src/main/resources/templates/main.html
- outpolic/src/main/resources/templates/user/search/userSearchView.html
> [outpolic-KHB] 중중간 커밋

- outpolic/src/main/resources/static/user/assets/css/main.css
- outpolic/src/main/resources/static/user/assets/css/userRanking.css
- outpolic/src/main/resources/templates/user/osst/userOutsourcingStatusList.html
- outpolic/src/main/resources/templates/user/search/userSearchView.html
detail : 진행중인 외주에서 리뷰페이지 뷰만 만들었음
> [outpolic-KHB] 리뷰 모달창 생성

- outpolic/src/main/resources/templates/enter/fragments/enterHeader.html
detail : 오류 발생으로 기업 헤더를 수정했습니다.
> [outpolic-LSJ] 기업 헤더 수정

- outpolic/src/main/java/outpolic/enter/main/controller/EnterHomeController.java
- outpolic/src/main/java/outpolic/user/main/controller/UserHomeController.java
- outpolic/src/main/resources/static/enter/assets/css/enterRanking.css
- outpolic/src/main/resources/static/enter/assets/css/main.css
- outpolic/src/main/resources/static/enter/assets/js/enterRanking.js
- outpolic/src/main/resources/static/enter/assets/js/main.js
- outpolic/src/main/resources/static/enter/assets/js/slick.js
- outpolic/src/main/resources/templates/enter/layout/enterLayoutMain.html
- outpolic/src/main/resources/templates/enterMain.html
- outpolic/src/main/resources/templates/main.html
- outpolic/src/main/resources/templates/user/contentsParticular/userContentsParticularView.html
- outpolic/src/main/resources/templates/user/search/userSearchView.html
> [outpolic-KHB] enter main 수정

- outpolic/src/main/java/outpolic/enter/main/controller/EnterHomeController.java
> [outpolic-KHB] 다시 푸시

- outpolic/src/main/java/outpolic/admin/category/controller/AdminCategoryController.java
- outpolic/src/main/java/outpolic/admin/statistics/controller/AdminStatisticsController.java
- outpolic/src/main/java/outpolic/admin/tag/controller/AdminTagController.java
- outpolic/src/main/resources/templates/admin/category/adminCategoryAddView.html
- outpolic/src/main/resources/templates/admin/category/adminCategoryEditView.html
- outpolic/src/main/resources/templates/admin/category/adminCategorySelectView.html
- outpolic/src/main/resources/templates/admin/category/adminCategoryeDeleteView.html
- outpolic/src/main/resources/templates/admin/fragments/adminAside.html
- outpolic/src/main/resources/templates/admin/statistics/adminContentsViewsStatisticsView.html
- outpolic/src/main/resources/templates/admin/statistics/adminRankingStatisticsView.html
- outpolic/src/main/resources/templates/admin/statistics/adminSearchStatisticsView.html
- outpolic/src/main/resources/templates/admin/tag/adminTagAddView.html
- outpolic/src/main/resources/templates/admin/tag/adminTagDeleteView.html
- outpolic/src/main/resources/templates/admin/tag/adminTagEditView.html
- outpolic/src/main/resources/templates/admin/tag/adminTagSelectView.html
detail : 관리자페이지 어사이드에 링크 넣고 컨트롤러 추가 등등
> [outpolic-KHB] 관리자페이지 뷰 추가

- outpolic/src/main/java/outpolic/user/payment/controller/UserPaymentController.java
- outpolic/src/main/resources/mapper/user/payment/UserPaymentMapper.xml
- outpolic/src/main/resources/templates/user/fragments/userHeader.html
- outpolic/src/main/resources/templates/user/goods/userGoodsList.html
detail : 헤더 모바일화면 수정했습니다.(미완성) 결제기능 데이터 저장부분 수정했습니다
> [outpolic-LSJ] 헤더 수정 및 결제기능 수정

- outpolic/src/main/resources/templates/admin/statistics/adminRankingStatisticsView.html
- outpolic/src/main/resources/templates/admin/statistics/adminSearchStatisticsView.html
- outpolic/src/main/resources/templates/admin/tag/adminTagAddView.html
- outpolic/src/main/resources/templates/admin/tag/adminTagDeleteView.html
- outpolic/src/main/resources/templates/admin/tag/adminTagEditView.html
- outpolic/src/main/resources/templates/admin/tag/adminTagSelectView.html
> [outpolic-KHB] 관리자 페이지 수정중

- outpolic/src/main/resources/mapper/user/payment/UserPaymentMapper.xml
- outpolic/src/main/resources/templates/user/goods/userGoodsList.html
detail : 초기화 버튼 누르고 취소를 눌러도 화면이 새로고침이 되고있는 오류를 발견돼서 오류 수정했습니다
> [outpolic-LSJ] 선택 초기화 버튼 수정

- outpolic/src/main/resources/templates/user/goods/userGoodsList.html
> [outpolic-LSJ] 버튼 삭제

- outpolic/pom.xml
- outpolic/src/main/java/outpolic/systems/config/SecurityConfig.java
- outpolic/src/main/java/outpolic/user/login/service/Impl/UserLoginServiceImpl.java
- outpolic/src/main/java/outpolic/user/register/service/Impl/UserRegisterServiceImpl.java
- outpolic/src/main/resources/templates/user/login/userLoginView.html
detail : 비밀번호 암호화 작업 완료. 로그인창에 기본값 user002 넣어놨습니다. 기업회원임 개인정보 어디까지 암호화해둘지 고민중입니다.
> [outpolic-SSY] 비밀번호 암호화 작업

- outpolic/src/main/resources/templates/admin/fragments/adminAside.html
- outpolic/src/main/resources/templates/enter/fragments/enterCategoryContainer.html
- outpolic/src/main/resources/templates/enter/fragments/enterFooter.html
- outpolic/src/main/resources/templates/enter/fragments/enterHeader.html
- outpolic/src/main/resources/templates/enter/fragments/enterNavi.html
- outpolic/src/main/resources/templates/enter/fragments/enterSidebar.html
detail : admin 페이지와 enter 페이지의 메뉴바에 .html 매핑되어 있는 부분을 #으로 모두 변경했습니다
> [outpolic-YSR] admin, enter 주소 매핑

- outpolic/src/main/resources/templates/user/fragments/userCategoryContainer.html
- outpolic/src/main/resources/templates/user/fragments/userFooter.html
- outpolic/src/main/resources/templates/user/fragments/userHeader.html
- outpolic/src/main/resources/templates/user/fragments/userMobileHeader.html
- outpolic/src/main/resources/templates/user/fragments/userSidebar.html
detail : html파일로 연결된 a태그 # 으로 변경 처리
> [outpolic-LSJ] 기능 주소 변경

- outpolic/src/main/resources/templates/enter/fragments/enterHeader.html
- outpolic/src/main/resources/templates/user/contentsParticular/userContentsParticularView.html
- outpolic/src/main/resources/templates/user/fragments/userHeader.html
detail : user, enter 메뉴바 매핑했습니다. 필요한 버튼 있으면 알아서 추가하시고, admin은 알아서 매핑하세용
> [outpolic-YSR] user, enter 메뉴바 수정

- outpolic/src/main/resources/templates/enter/fragments/enterCategorySidebar.html
- outpolic/src/main/resources/templates/enter/fragments/enterHeader.html
- outpolic/src/main/resources/templates/enter/layout/enterLayoutMain.html
> [outpolic-KHB] 엔터에 매핑된 유저로 가는 주소들 바꿈

- outpolic/src/main/java/outpolic/admin/category/controller/AdminCategoryController.java
> [outpolic-KHB] 풀 받기전 커밋

- outpolic/src/main/resources/static/enter/assets/css/enterChatRoom.css
- outpolic/src/main/resources/templates/enter/fragments/enterChatRoom.html
> [outpolic-YSR] enter 채팅 수정

- outpolic/src/main/java/outpolic/user/category/controller/UserCategoryController.java
- outpolic/src/main/resources/mapper/user/category/UsercategoryMapper.xml
detail : category앞에 user을 붙이는 과정중 생략해버림
> [outpolic-KHB] 카테고리 xml수정

- outpolic/src/main/java/outpolic/enter/mypage/controller/enterMypageController.java
- outpolic/src/main/java/outpolic/user/mypage/controller/UserMypageController.java
- outpolic/src/main/resources/templates/admin/login/adminLoginView.html
- outpolic/src/main/resources/templates/enter/fragments/enterHeader.html
- outpolic/src/main/resources/templates/user/fragments/userHeader.html
- outpolic/src/main/resources/templates/user/mypage/userMypageView.html
detail : 마이페이지로 이동하는 주소의 유저쪽은 앞에 /user, 기업쪽은 앞에 /enter 다 붙게 수정. 헤더 수정. 내 정보 수정으로 가는 화면에서 pw 암호화 로직 적용해서 수정
> [outpolic-SSY] 마이페이지쪽 주소 변경

- outpolic/src/main/resources/templates/enter/osst/enterOutsourcingStatusList.html
detail : 진행 외주 목록 페이지에서 박스 클릭하면 상세페이지 넘어가도록 수정했습니당
> [outpolic-YSR] 진행 외주 상세 페이지

- outpolic/src/main/resources/templates/enter/fragments/enterFooter.html
- outpolic/src/main/resources/templates/user/fragments/userFooter.html
detail : enter, user의 footer 수정했습니당
> [outpolic-YSR] Footer

- outpolic/src/main/resources/templates/projectInfo.html
detail : 포포리는 팀명으로 두고, OutPolic을 타이틀로 변경했습니당
> [outpolic-YSR] projectInfo 타이틀 수정

- outpolic/src/main/java/outpolic/user/category/controller/UserCategoryController.java
- outpolic/src/main/resources/templates/user/fragments/userNavi.html
> [outpolic-KHB] th문법 실수 수정

- outpolic/src/main/java/outpolic/admin/member/controller/adminMemberController.java
- outpolic/src/main/java/outpolic/admin/member/mapper/AdminMemberMapper.java
- outpolic/src/main/java/outpolic/admin/member/service/AdminMemberService.java
- outpolic/src/main/java/outpolic/admin/member/service/Impl/adminMemberServiceImpl.java
- outpolic/src/main/resources/mapper/admin/member/AdminMemberMapper.xml
- outpolic/src/main/resources/templates/admin/member/adminMemberListView.html
> [outpolic-SSY] 관리자 회원 페이지 제작중

- outpolic/src/main/java/outpolic/enter/osst/domain/EnterOsst.java
- outpolic/src/main/java/outpolic/enter/osst/domain/EnterOsstRecord.java
- outpolic/src/main/resources/mapper/enter/Osst/EnterOsstMapper.xml
- outpolic/src/main/resources/templates/enter/osst/enterOutsourcingStatusDetail.html
- outpolic/src/main/resources/templates/enter/osst/enterOutsourcingStatusList.html
> [outpolic-YSR] 중간커밋

- outpolic/src/main/java/outpolic/user/contents/controller/UserContentsController.java
- outpolic/src/main/java/outpolic/user/contents/mapper/UserContentViewMapper.java
detail : 인설트가 이상하게 되는 이유를 찾았습니다 이상한 쓰레기 데이터가 테이블안에 숨어있더라구요
> [outpolic-KHB] 오류해결

- outpolic/src/main/resources/templates/admin/member/adminMemberListView.html
[상세내용] 현재 한 화면에 나오는 내용이 너무 많아서 이걸 좀 줄이고 차라리 상세보기 화면을 구현할까 고민중. 구현한다면 모달창 느낌으로 띄울 예정.
> [outpolic-SSY] 관리자 회원목록 전화번호 마스킹

- outpolic/src/main/java/outpolic/admin/member/controller/adminMemberController.java
- outpolic/src/main/java/outpolic/admin/member/mapper/AdminMemberMapper.java
- outpolic/src/main/java/outpolic/admin/member/service/AdminMemberService.java
- outpolic/src/main/java/outpolic/admin/member/service/Impl/adminMemberServiceImpl.java
- outpolic/src/main/java/outpolic/common/domain/Member.java
- outpolic/src/main/resources/mapper/admin/member/AdminMemberMapper.xml
- outpolic/src/main/resources/templates/admin/fragments/adminAside.html
- outpolic/src/main/resources/templates/admin/member/adminActiveMemberListView.html
- outpolic/src/main/resources/templates/admin/member/adminDormantMemberListView.html
- outpolic/src/main/resources/templates/admin/member/adminWithdrawMemberListView.html
[상세 설명] 관리자 페이지의 회원뷰 구성. 전체/활성/휴면/탈퇴회원뷰를 만들고 제재회원은 따로 볼수있게 하려고 함.
> [outpolic-SSY] 회원뷰 생성

- outpolic/src/main/java/outpolic/user/search/domain/UserContentsDetailDTO.java
- outpolic/src/main/resources/mapper/user/search/UserSearchMapper.xml
- outpolic/src/main/resources/templates/main.html
- outpolic/src/main/resources/templates/user/layout/userLayoutMain.html
- outpolic/src/main/resources/templates/user/search/userSearchView.html
> [outpolic-KHB] 디자인 변경

- outpolic/src/main/resources/templates/enterMain.html
- outpolic/src/main/resources/templates/main.html
detail : 필요없는 요소 제거. 메인 페이지 상단 이미지에 필요없는 요소를 제거했습니다.
> [outpolic-LSJ] 메인페이지 수정

- outpolic/src/main/resources/static/admin/assets/js/main.js
- outpolic/src/main/resources/templates/admin/fragments/adminAside.html
- outpolic/src/main/resources/templates/admin/layout/adminLayoutMain.html
> [outpolic-KHB] 어사이트 수정

- outpolic/src/main/java/outpolic/admin/statistics/controller/AdminStatisticsController.java
- outpolic/src/main/java/outpolic/admin/statistics/domain/AdminPortfolioRankingContentsDTO.java
- outpolic/src/main/java/outpolic/admin/statistics/domain/AdminRankingContentsDTO.java
- outpolic/src/main/java/outpolic/admin/statistics/mapper/AdminRankingMapper.java
- outpolic/src/main/java/outpolic/admin/statistics/service/AdminRankingService.java
- outpolic/src/main/java/outpolic/admin/statistics/service/impl/AdminRankingServiceImpl.java
- outpolic/src/main/resources/mapper/admin/ranking/AdminRankingMapper.xml
- outpolic/src/main/resources/templates/admin/fragments/adminAside.html
> [outpolic-KHB] 어드민 어사이드 변경

- outpolic/src/main/java/outpolic/admin/statistics/controller/AdminStatisticsController.java
- outpolic/src/main/java/outpolic/admin/statistics/service/AdminRankingService.java
- outpolic/src/main/java/outpolic/admin/statistics/service/impl/AdminRankingServiceImpl.java
- outpolic/src/main/resources/templates/admin/statistics/adminRankingStatisticsView.html
detail : 서비스임플에 서비스 어노테이션 안넣어서 오류생김
> [outpolic-KHB] 오류발생해서 다시 커밋해용

- outpolic/src/main/java/outpolic/admin/points/controller/AdminPointsController.java
- outpolic/src/main/resources/templates/admin/fragments/adminAside.html
detail : 매핑 수정을 위해서 Aside(관리자) 수정했습니다
> [outpolic-LSJ] 매핑 수정 및 관리자 Aside 수정

- outpolic/src/main/resources/templates/admin/layout/adminLayoutLogin.html
- outpolic/src/main/resources/templates/admin/login/adminLoginView.html
- outpolic/src/main/resources/templates/admin/member/adminMemberListViewByStatus.html
- outpolic/src/main/resources/templates/projectInfo.html
> [outpolic-SSY] 프로젝트 인포 수정

- outpolic/src/main/resources/templates/enter/layout/enterLayoutContentsParticular.html
- outpolic/src/main/resources/templates/user/layout/userLayoutContentsParticular.html
- outpolic/src/main/resources/templates/user/layout/userLayoutListpage.html
- outpolic/src/main/resources/templates/user/search/userSearchView.html
detail : 엔터 상세컨텐츠 레이아웃, 유저 상세컨텐츠 레이아웃, 유저리스트페이지 레이아웃 건들였어용
> [outpolic-KHB] 레이아웃 변경

- outpolic/src/main/resources/static/user/assets/css/main.css
- outpolic/src/main/resources/static/user/assets/css/userInquiry.css
- outpolic/src/main/resources/templates/user/declaration/userDeclarationWriteView.html
- outpolic/src/main/resources/templates/user/fragments/userInquiryDetailSidebar.html
- outpolic/src/main/resources/templates/user/inquiry/userInquiryDetailView.html
- outpolic/src/main/resources/templates/user/inquiry/userInquiryFqaView.html
- outpolic/src/main/resources/templates/user/inquiry/userInquiryListView.html
- outpolic/src/main/resources/templates/user/inquiry/userInquiryNoticeView.html
- outpolic/src/main/resources/templates/user/inquiry/userInquiryTotalView.html
- outpolic/src/main/resources/templates/user/inquiry/userInquiryWriteView.html
- outpolic/src/main/resources/templates/user/layout/userLayoutInquiryDetail.html
detail : 1341.66 너비_user 문의/신고 다 맞췄습니당
> [outpolic-YSR] user 화면 수정

- outpolic/src/main/java/outpolic/enter/inquiry/domain/EnterInquiry.java
- outpolic/src/main/resources/mapper/enter/inquiry/EnterInquiryMapper.xml
- outpolic/src/main/resources/static/enter/assets/css/enterInquiry.css
- outpolic/src/main/resources/static/enter/assets/css/main.css
- outpolic/src/main/resources/templates/enter/declaration/enterDeclarationWriteView.html
- outpolic/src/main/resources/templates/enter/fragments/enterInquiryDetailSidebar.html
- outpolic/src/main/resources/templates/enter/inquiry/enterInquiryDetailView.html
- outpolic/src/main/resources/templates/enter/inquiry/enterInquiryFqaView.html
- outpolic/src/main/resources/templates/enter/inquiry/enterInquiryListView.html
- outpolic/src/main/resources/templates/enter/inquiry/enterInquiryNoticeView.html
- outpolic/src/main/resources/templates/enter/inquiry/enterInquiryTotalView.html
- outpolic/src/main/resources/templates/enter/inquiry/enterInquiryWriteView.html
- outpolic/src/main/resources/templates/enter/layout/enterLayoutInquiryDetail.html
- outpolic/src/main/resources/templates/user/layout/userLayoutInquiryList.html
detail : 1341.66 너비 enter 페이지 문의/신고 수정
> [outpolic-YSR] enter 화면 수정

- outpolic/src/main/resources/static/enter/assets/css/main.css
- outpolic/src/main/resources/templates/enter/layout/enterEditLayout.html
- outpolic/src/main/resources/templates/enter/mypage/enterEnterpriseInfoEditView.html
- outpolic/src/main/resources/templates/enter/mypage/enterProfileEditView.html
- outpolic/src/main/resources/templates/projectInfo.html
- outpolic/src/main/resources/templates/user/mypage/userProfileEditView.html
detail : 회원가입쪽 손 못댐. 프로젝트인포 링크중에 main관련된것들 안들어가짐. 수정요망
> [outpolic-SSY] 개인정보 수정 뷰와 css 수정하고 projectInfo 만들었음

- outpolic/src/main/resources/static/user/assets/js/userRegister.js
- outpolic/src/main/resources/templates/user/register/userRegisterView.html
detail : 회원가입 뷰 수정하고 이름에 영어 써도 입력되던 오류 수정
> [outpolic-SSY] 회원가입 뷰 수정

- outpolic/src/main/resources/templates/enterMain.html
- outpolic/src/main/resources/templates/main.html
detail : 세션별로 콘테이너 -> 로우 -> col-lg-10 m-auto로 변경
> [outpolic-KHB] 메인 레이아웃 깨지는 거 고쳤습니다

- outpolic/src/main/java/outpolic/admin/statistics/controller/AdminStatisticsController.java
- outpolic/src/main/java/outpolic/admin/statistics/mapper/AdminRankingMapper.java
- outpolic/src/main/java/outpolic/admin/statistics/service/AdminRankingService.java
- outpolic/src/main/java/outpolic/admin/statistics/service/impl/AdminRankingServiceImpl.java
- outpolic/src/main/resources/mapper/admin/ranking/AdminRankingMapper.xml
- outpolic/src/main/resources/templates/admin/statistics/adminRankingStatisticsView.html
> [outpolic-KHB] 어드민 랭킹뷰

- outpolic/src/main/java/outpolic/user/settlement/dto/UserSettlement.java
detail : 결제내역을 불러오기 위한 dto 클래스를 생성
> [outpolic-LSJ] 결제내역 기능 생성

- outpolic/src/main/resources/templates/main.html
> [outpolic-KHB] 주요기능

- outpolic/src/main/java/outpolic/admin/statistics/controller/AdminStatisticsApiController.java
- outpolic/src/main/java/outpolic/admin/statistics/controller/AdminStatisticsController.java
- outpolic/src/main/java/outpolic/admin/statistics/domain/AdminSearchStatisticsDTO.java
- outpolic/src/main/java/outpolic/admin/statistics/mapper/AdminSearchStatisticsMapper.java
- outpolic/src/main/java/outpolic/admin/statistics/service/AdminSearchStatisticsService.java
- outpolic/src/main/java/outpolic/admin/statistics/service/impl/AdminSearchStatisticsServiceImpl.java
- outpolic/src/main/java/outpolic/user/contents/controller/UserContentsController.java
- outpolic/src/main/java/outpolic/user/contents/domain/UserTodayView.java
- outpolic/src/main/java/outpolic/user/contents/mapper/UserTodayViewMapper.java
- outpolic/src/main/java/outpolic/user/contents/service/impl/UserContentViewServiceImpl.java
- outpolic/src/main/java/outpolic/user/search/controller/UserSearchController.java
- outpolic/src/main/java/outpolic/user/search/mapper/UserSearchHistoryMapper.java
- outpolic/src/main/java/outpolic/user/search/service/UserSearchHistoryService.java
- outpolic/src/main/java/outpolic/user/search/service/impl/UserSearchHistoryServiceImpl.java
- outpolic/src/main/resources/mapper/admin/searchStatistics/adminSearchStatisticsMapper.xml
- outpolic/src/main/resources/mapper/user/contentView/UserTodayViewMapper.xml
- outpolic/src/main/resources/mapper/user/search/UserSearchHistoryMapper.xml
- outpolic/src/main/resources/templates/admin/statistics/adminSearchStatisticsView.html
- outpolic/src/main/resources/templates/user/layout/userLayoutMain.html
> [outpolic-KHB] 조회수 기능 유저쪽만

- outpolic/src/main/java/outpolic/enter/contents/controller/EnterContentsController.java
- outpolic/src/main/java/outpolic/enter/contents/domain/EnterPerusalContent.java
- outpolic/src/main/java/outpolic/enter/contents/domain/EnterTodayView.java
- outpolic/src/main/java/outpolic/enter/contents/domain/EnterTotalView.java
- outpolic/src/main/java/outpolic/enter/contents/mapper/EnterContentViewMapper.java
- outpolic/src/main/java/outpolic/enter/contents/mapper/EnterTodayViewMapper.java
- outpolic/src/main/java/outpolic/enter/contents/service/EnterContentViewService.java
- outpolic/src/main/java/outpolic/enter/contents/service/impl/EnterContentViewServiceImpl.java
- outpolic/src/main/java/outpolic/enter/main/controller/EnterHomeController.java
- outpolic/src/main/java/outpolic/enter/search/controller/EnterSearchController.java
- outpolic/src/main/java/outpolic/enter/search/mapper/EnterSearchHistoryMapper.java
- outpolic/src/main/java/outpolic/enter/search/service/EnterSearchHistoryService.java
- outpolic/src/main/java/outpolic/enter/search/service/impl/EnterSearchHistoryServiceImpl.java
- outpolic/src/main/java/outpolic/user/contents/controller/UserContentsController.java
- outpolic/src/main/resources/mapper/enter/contentView/EnterContentViewMapper.xml
- outpolic/src/main/resources/mapper/enter/contentView/EnterTodayViewMapper.xml
- outpolic/src/main/resources/mapper/enter/search/EnterSearchHistoryMapper.xml
- outpolic/src/main/resources/mapper/user/search/UserSearchMapper.xml
- outpolic/src/main/resources/templates/enter/contentsParticular/enterContentsParticularView.html
- outpolic/src/main/resources/templates/enter/layout/enterLayoutMain.html
- outpolic/src/main/resources/templates/enterMain.html
> [outpolic-KHB] 오류안날때 후다닥 커밋

- outpolic/src/main/java/outpolic/admin/login/controller/adminLoginController.java
- outpolic/src/main/java/outpolic/admin/login/mapper/AdminLoginMapper.java
- outpolic/src/main/java/outpolic/admin/login/service/Impl/AdminLoginServiceImpl.java
- outpolic/src/main/resources/mapper/admin/login/AdminLoginMapper.xml
> [outpolic-SSY] 관리자 로그인 수정

- outpolic/src/main/java/outpolic/admin/member/controller/adminMemberController.java
- outpolic/src/main/java/outpolic/admin/member/mapper/AdminMemberMapper.java
- outpolic/src/main/java/outpolic/admin/member/service/AdminMemberService.java
- outpolic/src/main/java/outpolic/admin/member/service/Impl/adminMemberServiceImpl.java
- outpolic/src/main/resources/mapper/admin/member/AdminMemberMapper.xml
- outpolic/src/main/resources/templates/admin/member/adminMemberListView.html
detail : 오류나지말아라 제발. 다른 회원 페이지는 삭제할 예정. 근데 회원 목록 페이지가 저거 하나여도 되나?
> [outpolic-SSY] 관리자 회원 페이지 필터랑 검색기능 추가

- outpolic/src/main/resources/templates/user/contents/userContentsView.html
- outpolic/src/main/resources/templates/user/layout/userLayoutListpage.html
> [outpolic-KHB] 조쌤 피드백 1개 완료

- outpolic/src/main/java/outpolic/user/mypage/controller/UserMypageController.java
- outpolic/src/main/java/outpolic/user/mypage/dto/OutsourcingReviewDTO.java
- outpolic/src/main/java/outpolic/user/mypage/mapper/UserMypageEditMapper.java
- outpolic/src/main/java/outpolic/user/mypage/service/Impl/UserMypageEditServiceImpl.java
- outpolic/src/main/java/outpolic/user/mypage/service/UserMypageEditService.java
- outpolic/src/main/resources/mapper/user/mypageEdit/UserMypageMapper.xml
- outpolic/src/main/resources/templates/user/mypage/userMypageView.html
[detail] 마이페이지에 리뷰 불러왔음. 문의쪽 건드리다가 죄다 건드려야하게 생겨서 내일하려고 커밋함.
> [outpolic-SSY] 마이페이지 리뷰 불러오기 구현

- outpolic/src/main/java/outpolic/user/goods/controller/userGoodsController.java
- outpolic/src/main/java/outpolic/user/points/dto/UserPointsDTO.java
- outpolic/src/main/java/outpolic/user/points/mapper/UserPointsMapper.java
- outpolic/src/main/java/outpolic/user/points/service/UserPointsService.java
- outpolic/src/main/java/outpolic/user/points/service/impl/UserPointsServiceImpl.java
- outpolic/src/main/resources/mapper/user/points/UserPointsMapper.xml
- outpolic/src/main/resources/templates/user/goods/userGoodsList.html
detail : 결제페이지에서 보유하고 있는 마일리지 조회하는 기능 생성 및 작업중
> [outpolic-LSJ] 결제페이지 수정

- outpolic/src/main/resources/templates/enter/fragments/enterHeader.html
- outpolic/src/main/resources/templates/enterMain.html
detail : 모바일 헤더 로고 예전꺼로 되어있는거 수정하고 enterMain ui 수정
> [outpolic-SSY] 모바일 로고 찐빠난거 변경

- outpolic/src/main/resources/templates/enterMain.html
> [outpolic-SSY] 주요기능

- outpolic/src/main/resources/templates/admin/inquiry/adminInquiryResourcesView.html
- outpolic/src/main/resources/templates/admin/inquiry/adminInquiryView.html
- outpolic/src/main/resources/templates/admin/osst/adminOutsourcingStatusView.html
detail : 관리자 목록 자원 변경했어요. 나머지 집가서 함
> [outpolic-YSR] 목록자원

- outpolic/src/main/java/outpolic/admin/login/controller/adminLoginController.java
- outpolic/src/main/java/outpolic/admin/login/dto/AdminLoginDTO.java
- outpolic/src/main/java/outpolic/admin/login/mapper/AdminLoginMapper.java
- outpolic/src/main/java/outpolic/admin/login/service/Impl/AdminLoginServiceImpl.java
- outpolic/src/main/resources/mapper/admin/login/AdminLoginMapper.xml
- outpolic/src/main/resources/templates/user/mypage/userMypageView.html
> [outpolic-SSY] dto 소문자로 변경

- outpolic/src/main/java/outpolic/admin/category/controller/AdminCategoryController.java
- outpolic/src/main/java/outpolic/admin/category/mapper/AdminCategoryMapper.java
- outpolic/src/main/java/outpolic/admin/category/service/AdminCategoryService.java
- outpolic/src/main/java/outpolic/admin/category/service/impl/AdminCategoryServiceImpl.java
- outpolic/src/main/resources/mapper/admin/category/adminCategoryMapper.xml
- outpolic/src/main/resources/templates/admin/category/adminCategorySelectView.html
- outpolic/src/main/resources/templates/admin/statistics/adminContentsViewsStatisticsView.html
- outpolic/src/main/resources/templates/admin/statistics/adminRankingStatisticsView.html
- outpolic/src/main/resources/templates/admin/statistics/adminSearchStatisticsView.html
> [outpolic-KHB] 카테고리 삭제버튼 추가

- outpolic/src/main/java/outpolic/enter/goods/controller/EnterGoodsController.java
- outpolic/src/main/java/outpolic/enter/mypage/controller/enterMypageController.java
- outpolic/src/main/java/outpolic/enter/points/dto/EnterPointsDTO.java
- outpolic/src/main/java/outpolic/enter/points/mapper/EnterPointsMapper.java
- outpolic/src/main/java/outpolic/enter/points/service/EnterPointsService.java
- outpolic/src/main/java/outpolic/enter/points/service/impl/EnterPointsServiceImpl.java
- outpolic/src/main/java/outpolic/systems/payment/controller/PaymentController.java
- outpolic/src/main/java/outpolic/systems/payment/dto/SettlementDTO.java
- outpolic/src/main/java/outpolic/user/goods/controller/UserGoodsController.java
- outpolic/src/main/java/outpolic/user/points/service/UserPointsService.java
- outpolic/src/main/resources/mapper/enter/points/EnterPointsMapper.xml
- outpolic/src/main/resources/templates/enter/goods/enterGoodsList.html
- outpolic/src/main/resources/templates/user/goods/userGoodsList.html
detail : 기업의 마일리지 조회 기능을 추가했습니다. (그런데 마일리지 유효성검사 로직이 안먹혀서 마일리지 없애버릴까 진지하게 고민중;;)
> [outpolic-LSJ] 마일리지 기능 추가

- outpolic/src/main/java/outpolic/enter/portfolio/controller/EnterPortfolioController.java
- outpolic/src/main/java/outpolic/enter/portfolio/service/impl/EnterPortfolioServiceImpl.java
- outpolic/src/main/resources/templates/enter/outsourcing/outsourcingListView.html
- outpolic/src/main/resources/templates/enter/portfolio/editPortfolio.html
detail: 외주 EnterPortfolioServiceImpl오류 수정난 부분 고쳤습니다.
> [outpolic-KJW]  외주 수정

- outpolic/src/main/java/outpolic/enter/search/controller/EnterBookmarkApiController.java
- outpolic/src/main/java/outpolic/enter/search/domain/EnterBookmark.java
- outpolic/src/main/java/outpolic/enter/search/domain/EnterContentItemDTO.java
- outpolic/src/main/java/outpolic/enter/search/mapper/EnterBookmarkMapper.java
- outpolic/src/main/java/outpolic/enter/search/service/EnterBookmarkService.java
- outpolic/src/main/java/outpolic/enter/search/service/impl/EnterBookmarkServiceImpl.java
- outpolic/src/main/resources/mapper/enter/bookmark/EnterBookmarkMapper.xml
- outpolic/src/main/resources/mapper/enter/search/EnterSearchMapper.xml
- outpolic/src/main/resources/templates/enter/contents/enterContentsView.html
- outpolic/src/main/resources/templates/enter/layout/enterLayoutListpage.html
> [outpolic-KHB] 북마크 생성 완

- outpolic/src/main/java/outpolic/enter/outsourcingRequest/controller/OutsourcingRequestController.java
- outpolic/src/main/java/outpolic/enter/outsourcingRequest/domain/OutsourcingRequestDTO.java
- outpolic/src/main/java/outpolic/enter/outsourcingRequest/domain/RequestViewDTO.java
- outpolic/src/main/java/outpolic/enter/outsourcingRequest/mapper/EnterOutsourcingRequestMapper.java
- outpolic/src/main/java/outpolic/enter/outsourcingRequest/service/OutsourcingRequestService.java
- outpolic/src/main/java/outpolic/enter/outsourcingRequest/service/impl/OutsourcingRequestServiceImpl.java
- outpolic/src/main/java/outpolic/enter/portfolio/service/impl/EnterPortfolioServiceImpl.java
- outpolic/src/main/java/outpolic/enter/portfolio/service/impl/PortfolioAsyncService.java
- outpolic/src/main/resources/templates/enter/outsourcingRequest/requestDetailView.html
detail: 보낸 외주 신청상세페이지에서 승인과거절을 제거했습니다.
> [outpolic-KJW]  외주 신청 부분 기능 어느정도 완료

- outpolic/src/main/java/outpolic/user/ranking/domain/UserPortfolioRankingContentsDTO.java
- outpolic/src/main/java/outpolic/user/ranking/domain/UserRankingContentsDTO.java
- outpolic/src/main/resources/mapper/user/ranking/UserRankingMapper.xml
- outpolic/src/main/resources/templates/main.html
- outpolic/src/main/resources/templates/user/fragments/userBookmarkButton.html
detail : 엔터쪽도 다해야하니까 내일 사랑이가 해줘야 할듯 ㅠ
> [outpolic-KHB] 포트폴리오 상세페이지에서 문의하기 버튼, 즐찾 버튼 및 메인화면에서 즐찾 기능

- outpolic/src/main/java/outpolic/admin/goods/controller/AdminGoodsController.java
- outpolic/src/main/java/outpolic/admin/goods/dto/AdminGoodsDTO.java
- outpolic/src/main/java/outpolic/admin/goods/mapper/AdminGoodsMapper.java
- outpolic/src/main/java/outpolic/admin/goods/service/AdminGoodsService.java
- outpolic/src/main/java/outpolic/admin/goods/service/impl/AdminGoodsServiceImpl.java
- outpolic/src/main/resources/mapper/admin/goods/AdminGoodsMapper.xml
- outpolic/src/main/resources/templates/admin/goods/adminGoodsSelectView.html
detail : 관리자페이지에서 상품 관리 기능 추가했습니다.
> [outpolic-LSJ] 관리자페이지 상품내역 결과 노출

- outpolic/src/main/java/outpolic/admin/osst/controller/AdminOsstController.java
- outpolic/src/main/java/outpolic/admin/osst/domain/AdminOsst.java
- outpolic/src/main/java/outpolic/admin/osst/mapper/AdminOsstMapper.java
- outpolic/src/main/java/outpolic/admin/osst/service/AdminOsstService.java
- outpolic/src/main/java/outpolic/admin/osst/service/Impl/AdminOsstServiceImpl.java
- outpolic/src/main/resources/mapper/admin/osst/AdminOsstMapper.xml
- outpolic/src/main/resources/templates/admin/osst/adminOutsourcingStatusView.html
> [outpolic-YSR] 외주 진행 관리자

- outpolic/src/main/java/outpolic/systems/interceptor/LogInterceptor.java
- outpolic/src/main/resources/templates/user/layout/userLayoutContentsParticular.html
- outpolic/src/main/resources/templates/user/layout/userLayoutInquiryDetail.html
- outpolic/src/main/resources/templates/user/layout/userLayoutInquiryList.html
- outpolic/src/main/resources/templates/user/layout/userLayoutInquiryWrite.html
- outpolic/src/main/resources/templates/user/layout/userLayoutListpage.html
- outpolic/src/main/resources/templates/user/layout/userRegisterLayout.html
detail : 접속로그 클라이언트 실제 ip 주소 수정 및 타입리프 링크문법 수정
> [outpolic-YSR] 접속로그 수정 및 주소매핑 수정

- outpolic/src/main/resources/mapper/enter/mypage/EnterMypageMapper.xml
- outpolic/src/main/resources/templates/enter/mypage/enterMypageView.html
> [outpolic-SSY] 풀받으려고 커밋

- outpolic/src/main/java/outpolic/enter/ranking/domain/EnterPortfolioRankingContentsDTO.java
- outpolic/src/main/java/outpolic/enter/ranking/domain/EnterRankingContentsDTO.java
- outpolic/src/main/java/outpolic/user/contents/controller/UserContentsController.java
- outpolic/src/main/java/outpolic/user/main/controller/UserHomeController.java
- outpolic/src/main/java/outpolic/user/ranking/mapper/UserRankingMapper.java
- outpolic/src/main/java/outpolic/user/ranking/service/UserRankingService.java
- outpolic/src/main/java/outpolic/user/ranking/service/impl/UserRankingServiceImpl.java
- outpolic/src/main/java/outpolic/user/search/domain/UserContentsDetailDTO.java
- outpolic/src/main/java/outpolic/user/search/mapper/UserSearchMapper.java
- outpolic/src/main/java/outpolic/user/search/service/UserSearchService.java
- outpolic/src/main/java/outpolic/user/search/service/impl/UserSearchServiceImpl.java
- outpolic/src/main/resources/mapper/enter/bookmark/EnterBookmarkMapper.xml
- outpolic/src/main/resources/mapper/enter/ranking/EnterRankingMapper.xml
- outpolic/src/main/resources/mapper/user/ranking/UserRankingMapper.xml
- outpolic/src/main/resources/mapper/user/search/UserSearchMapper.xml
- outpolic/src/main/resources/templates/enter/fragments/enterBookmarkButton.html
- outpolic/src/main/resources/templates/enterMain.html
- outpolic/src/main/resources/templates/main.html
> [outpolic-KHB] 북마크 수정

- outpolic/src/main/java/outpolic/enter/contents/controller/EnterContentsController.java
- outpolic/src/main/java/outpolic/enter/main/controller/EnterHomeController.java
- outpolic/src/main/java/outpolic/enter/ranking/mapper/EnterRankingMapper.java
- outpolic/src/main/java/outpolic/enter/ranking/service/EnterRankingService.java
- outpolic/src/main/java/outpolic/enter/ranking/service/impl/EnterRankingServiceImpl.java
- outpolic/src/main/java/outpolic/enter/search/domain/EnterContentsDetailDTO.java
- outpolic/src/main/java/outpolic/enter/search/mapper/EnterSearchMapper.java
- outpolic/src/main/java/outpolic/enter/search/service/EnterSearchService.java
- outpolic/src/main/java/outpolic/enter/search/service/impl/EnterSearchServiceImpl.java
- outpolic/src/main/java/outpolic/user/main/controller/UserHomeController.java
- outpolic/src/main/java/outpolic/user/ranking/service/impl/UserRankingServiceImpl.java
- outpolic/src/main/java/outpolic/user/search/domain/UserContentItemDTO.java
- outpolic/src/main/java/outpolic/user/search/domain/UserContentsDetailDTO.java
- outpolic/src/main/java/outpolic/user/search/service/impl/UserSearchServiceImpl.java
- outpolic/src/main/resources/mapper/enter/ranking/EnterRankingMapper.xml
- outpolic/src/main/resources/mapper/enter/search/EnterSearchMapper.xml
- outpolic/src/main/resources/mapper/user/ranking/UserRankingMapper.xml
- outpolic/src/main/resources/mapper/user/search/UserSearchMapper.xml
- outpolic/src/main/resources/templates/enter/contents/enterContentsView.html
- outpolic/src/main/resources/templates/enterMain.html
- outpolic/src/main/resources/templates/user/contents/userContentsView.html
- outpolic/src/main/resources/templates/user/layout/userLayoutListpage.html
detail : 한쪽에 먼저 만들고 다른쪽에 붙여넣기 했어요
> [outpolic-KHB] 유저 페이지 엔터 페이지 즐찾 기능 똑같이

- outpolic/src/main/resources/mapper/user/search/UserSearchMapper.xml
> [outpolic-KHB]포트폴리오 안들어가지는 소소한 오류 수정

- outpolic/src/main/java/outpolic/admin/goods/controller/AdminGoodsController.java
- outpolic/src/main/java/outpolic/admin/goods/dto/AdminGoodsDTO.java
- outpolic/src/main/java/outpolic/admin/goods/service/impl/AdminGoodsServiceImpl.java
- outpolic/src/main/resources/mapper/admin/goods/AdminGoodsMapper.xml
- outpolic/src/main/resources/templates/admin/goods/adminGoodsSelectView.html
detail : 관리자 상품 관리 페이지 등록하기 구현 완료했습니다.
> [outpolic-LSJ] 관리자 상품 페이지 수정

- outpolic/src/main/java/outpolic/admin/statistics/controller/AdminStatisticsApiController.java
- outpolic/src/main/java/outpolic/admin/statistics/mapper/AdminSearchStatisticsMapper.java
- outpolic/src/main/java/outpolic/admin/statistics/service/AdminSearchStatisticsService.java
- outpolic/src/main/java/outpolic/admin/statistics/service/impl/AdminSearchStatisticsServiceImpl.java
- outpolic/src/main/resources/mapper/admin/searchStatistics/adminSearchStatisticsMapper.xml
- outpolic/src/main/resources/templates/admin/layout/adminLayoutMain.html
- outpolic/src/main/resources/templates/admin/statistics/adminRankingStatisticsView.html
- outpolic/src/main/resources/templates/admin/statistics/adminSearchStatisticsView.html
detail : 관리자페이지 필터 안먹던것들 기능 추가했어요
> [outpolic-KHB] 집가기전 커밋 앤 푸쉬헤드~

- outpolic/src/main/resources/mapper/user/login/UserLoginMapper.xml
> [outpolic-SSY] 로그인 mapper 수정

- outpolic/src/main/java/outpolic/user/declaration/controller/UserDeclarationController.java
- outpolic/src/main/java/outpolic/user/declaration/domain/UserDeclaration.java
- outpolic/src/main/java/outpolic/user/declaration/mapper/UserDeclarationMapper.java
- outpolic/src/main/java/outpolic/user/declaration/service/Impl/UserDeclarationServiceImpl.java
- outpolic/src/main/java/outpolic/user/declaration/service/UserDeclarationService.java
- outpolic/src/main/resources/mapper/user/declaration/UserDeclarationMapper.xml
- outpolic/src/main/resources/templates/user/declaration/userDeclarationWriteView.html
> [outpolic-YSR] user 신고 페이지

- outpolic/src/main/java/outpolic/user/mypage/controller/UserMypageController.java
- outpolic/src/main/java/outpolic/user/mypage/dto/MypageDTO.java
- outpolic/src/main/java/outpolic/user/mypage/dto/UserOsInfoDTO.java
- outpolic/src/main/java/outpolic/user/mypage/mapper/UserMypageEditMapper.java
- outpolic/src/main/java/outpolic/user/mypage/service/Impl/UserMypageEditServiceImpl.java
- outpolic/src/main/java/outpolic/user/mypage/service/UserMypageEditService.java
- outpolic/src/main/java/outpolic/user/outsourcing/dto/UserOsInfoDTO.java
- outpolic/src/main/java/outpolic/user/outsourcing/mapper/UserOutsourcingMapper.java
- outpolic/src/main/java/outpolic/user/outsourcing/service/Impl/UserOutsourcingServiceImpl.java
- outpolic/src/main/java/outpolic/user/outsourcing/service/UserOutsourcingService.java
- outpolic/src/main/java/outpolic/user/withdrawn/controller/UserWithdrawnController.java
- outpolic/src/main/resources/mapper/user/mypageEdit/UserMypageMapper.xml
- outpolic/src/main/resources/mapper/user/mypageEdit/UserMypageOsMapper.xml
- outpolic/src/main/resources/templates/user/fragments/userMypageAside.html
- outpolic/src/main/resources/templates/user/layout/userMypageLayout.html
- outpolic/src/main/resources/templates/user/mypage/userMypageView.html
- outpolic/src/main/resources/templates/user/withdrawn/userWithdrawnView.html
detail : 외주 진행 내역 있으면 탈퇴 못하게 보강 완료. 이제 진짜 enter 회원 탈퇴 작성
> [outpolic-SSY] 일반회원 회원탈퇴 보강

- outpolic/src/main/java/outpolic/user/bookmark/controller/UserBookmarkController.java
- outpolic/src/main/java/outpolic/user/bookmark/dto/UserBookmarkViewDTO.java
- outpolic/src/main/java/outpolic/user/bookmark/mapper/UserBookmarkMapper.java
- outpolic/src/main/resources/mapper/user/bookmark/UserBookmarkMapper.xml
- outpolic/src/main/resources/templates/user/bookmark/userBookmarkView.html
- outpolic/src/main/resources/templates/user/fragments/userBookmarkSidebar.html
- outpolic/src/main/resources/templates/user/fragments/userHeader.html
- outpolic/src/main/resources/templates/user/layout/userLayoutBookmark.html
detail : 즐겨찾기 뷰 만들고 한별이꺼 레이아웃도 수정함. 쿼리까지 짜둬서 집가서 데이터 매핑 할 수도있고 아닐수도있고
> [outpolic-SSY] 즐겨찾기 뷰 제작

- outpolic/src/main/java/outpolic/admin/declaration/controller/AdminDeclarationController.java
- outpolic/src/main/java/outpolic/admin/declaration/domain/AdminDeclaration.java
- outpolic/src/main/java/outpolic/admin/declaration/domain/SubmissionAttachment.java
- outpolic/src/main/java/outpolic/admin/declaration/mapper/AdminDeclarationMapper.java
- outpolic/src/main/java/outpolic/admin/declaration/service/AdminDeclarationService.java
- outpolic/src/main/java/outpolic/admin/declaration/service/Impl/AdminDeclarationServiceImpl.java
- outpolic/src/main/resources/mapper/admin/declaration/AdminDeclarationMapper.xml
- outpolic/src/main/resources/templates/admin/declaration/adminDeclarationView.html
> [outpolic-YSR] 신고 저장 오류만 고치면 되는데 이 거지같은

- outpolic/src/main/java/outpolic/admin/limits/controller/AdminLimitsController.java
- outpolic/src/main/java/outpolic/admin/limits/domain/AdminLimits.java
- outpolic/src/main/java/outpolic/admin/limits/mapper/AdminLimitsMapper.java
- outpolic/src/main/java/outpolic/admin/limits/service/AdminLimitsService.java
- outpolic/src/main/java/outpolic/admin/limits/service/Impl/AdminLimitsServiceImpl.java
- outpolic/src/main/resources/mapper/admin/limits/AdminLimitsMapper.xml
- outpolic/src/main/resources/templates/admin/limits/adminLimitsResourcesView.html
detail : 제재 타입, 기간 탭의 등록, 수정 프로세스 완료. 제재 사유 탭의 등록, 수정, 상세만 남음. 중간커밋.
> [outpolic-YSR] admin 제재 자원 관리

- outpolic/src/main/java/outpolic/user/bookmark/controller/UserBookmarkController.java
- outpolic/src/main/java/outpolic/user/bookmark/dto/UserBookmarkViewDTO.java
- outpolic/src/main/java/outpolic/user/bookmark/mapper/UserBookmarkMapper.java
- outpolic/src/main/java/outpolic/user/bookmark/service/Impl/UserBookmarkServiceImpl.java
- outpolic/src/main/java/outpolic/user/bookmark/service/UserBookmarkService.java
- outpolic/src/main/java/outpolic/user/bookmark/service/UserBookmartService.java
- outpolic/src/main/resources/mapper/user/bookmark/UserBookmarkMapper.xml
- outpolic/src/main/resources/templates/user/bookmark/userBookmarkView.html
> [outpolic-SSY] 화제밸 울려서 급하게 커밋

- outpolic/src/main/java/outpolic/user/bookmark/dto/UserBookmarkViewDTO.java
- outpolic/src/main/resources/mapper/user/bookmark/UserBookmarkMapper.xml
- outpolic/src/main/resources/templates/user/bookmark/userBookmarkView.html
detail : 북마크 뷰 완성되서 왼쪽 사이드바 작업 할 예정
> [outpolic-SSY] 북마크 뷰는 완성

- outpolic/src/main/resources/templates/user/bookmark/userBookmarkView.html
- outpolic/src/main/resources/templates/user/fragments/userBookmarkSidebar.html
[상세내용] 탭 기능까지 끝냄. (모달창 빼고) 그런데 지금 외주글이 안불러와집니다. 무슨일이 있었던건가요
> [outpolic-SSY] 유저 북마크 끝

- outpolic/src/main/java/outpolic/enter/mypage/controller/enterMypageController.java
- outpolic/src/main/java/outpolic/user/bookmark/controller/UserBookmarkController.java
- outpolic/src/main/resources/templates/enter/fragments/enterHeader.html
- outpolic/src/main/resources/templates/user/bookmark/userBookmarkView.html
- outpolic/src/main/resources/templates/user/fragments/userBookmarkSidebar.html
- outpolic/src/main/resources/templates/user/fragments/userHeader.html
- outpolic/src/main/resources/templates/user/layout/userLayoutBookmark.html
[상세설명] 추가로 ui 다듬고 찜한게 없을때엔 안내문 출력하게 함.
> [outpolic-SSY] enter도 bookmark 공유하기로 함

- outpolic/src/main/java/outpolic/admin/limits/controller/AdminLimitsController.java
- outpolic/src/main/java/outpolic/admin/limits/domain/AdminLimits.java
- outpolic/src/main/java/outpolic/admin/limits/service/AdminLimitsService.java
- outpolic/src/main/java/outpolic/admin/limits/service/Impl/AdminLimitsServiceImpl.java
- outpolic/src/main/resources/mapper/admin/limits/AdminLimitsMapper.xml
- outpolic/src/main/resources/templates/admin/limits/adminLimitsResourcesView.html
> [outpolic-YSR] 제재 기능

- outpolic/src/main/resources/mapper/user/search/UserSearchMapper.xml
- outpolic/src/main/resources/templates/user/contentsParticular/userContentsParticularView.html
> [outpolic-KHB] dto 오류 수정

- outpolic/src/main/java/outpolic/enter/osst/controller/EnterOsstController.java
- outpolic/src/main/java/outpolic/enter/osst/domain/EnterOsst.java
- outpolic/src/main/java/outpolic/enter/osst/mapper/EnterOsstMapper.java
- outpolic/src/main/java/outpolic/enter/osst/service/EnterOsstService.java
- outpolic/src/main/java/outpolic/enter/osst/service/Impl/EnterOsstServiceImpl.java
- outpolic/src/main/resources/mapper/enter/Osst/EnterOsstMapper.xml
- outpolic/src/main/resources/static/enter/assets/css/enterOutsourcingStatus.css
- outpolic/src/main/resources/templates/enter/osst/enterOutsourcingStatusDetail.html
- outpolic/src/main/resources/templates/enter/osst/enterOutsourcingStatusList.html
> [outpolic-YSR] 외주 진행 데이터

- outpolic/src/main/java/outpolic/admin/goods/controller/AdminGoodsController.java
- outpolic/src/main/java/outpolic/admin/goods/mapper/AdminGoodsMapper.java
- outpolic/src/main/java/outpolic/admin/goods/service/AdminGoodsService.java
- outpolic/src/main/java/outpolic/admin/goods/service/impl/AdminGoodsServiceImpl.java
- outpolic/src/main/resources/mapper/admin/goods/AdminGoodsMapper.xml
- outpolic/src/main/resources/templates/admin/goods/adminGoodsSelectView.html
> [outpolic-LSJ] 관리자페이지 상품 검색기능 추가

- outpolic/src/main/java/outpolic/user/category/controller/UserCategoryController.java
- outpolic/src/main/java/outpolic/user/search/domain/UserContentItemDTO.java
- outpolic/src/main/java/outpolic/user/search/mapper/UserSearchMapper.java
- outpolic/src/main/java/outpolic/user/search/service/UserSearchService.java
- outpolic/src/main/java/outpolic/user/search/service/impl/UserSearchServiceImpl.java
- outpolic/src/main/resources/mapper/user/ranking/UserRankingMapper.xml
- outpolic/src/main/resources/mapper/user/search/UserSearchMapper.xml
- outpolic/src/main/resources/templates/user/contents/userContentsView.html
detail : 이제 할거 ? 거의 없음(enter,리뷰 인설트문,관리자 페이지, 태그는 그냥 버릴게요)정도?
> [outpolic-KHB] 거의 모든 찐빠 없앰(user)

- outpolic/src/main/java/outpolic/enter/osst/controller/EnterOsstController.java
- outpolic/src/main/java/outpolic/enter/osst/domain/EnterStepData.java
- outpolic/src/main/java/outpolic/enter/osst/mapper/EnterOsstMapper.java
- outpolic/src/main/java/outpolic/enter/osst/service/EnterOsstService.java
- outpolic/src/main/java/outpolic/enter/osst/service/Impl/EnterOsstServiceImpl.java
- outpolic/src/main/resources/mapper/enter/Osst/EnterOsstMapper.xml
- outpolic/src/main/resources/templates/enter/osst/enterOutsourcingStatusDetail.html
- outpolic/src/main/resources/templates/user/fragments/userHeader.html
> [outpolic-YSR] 진행 외주

- outpolic/src/main/resources/mapper/user/ranking/UserRankingMapper.xml
- outpolic/src/main/resources/templates/main.html
- outpolic/src/main/resources/templates/user/contentsParticular/userContentsParticularView.html
detail : 집에서 할꺼(유저에서 만든것들 엔터로 옮기기, 북마크 위치 조절, 메인화면 최근 리뷰, 회사페이지 이미지 및 경로 지정 , 리뷰기능 만들기) 과연 집에서 다 만들고 올 수 있을것인가...
> [outpolic-KHB] 집가기전 커밋

- outpolic/src/main/resources/static/user/assets/css/userOutsourcingStatus.css
- outpolic/src/main/resources/templates/user/fragments/userHeader.html
- outpolic/src/main/resources/templates/user/layout/userLayoutOsstList.html
> [outpolic-YSR] user 진행외주 완료

- outpolic/src/main/java/outpolic/user/company/domain/UserCompanyOutsourcingDTO.java
- outpolic/src/main/java/outpolic/user/company/domain/UserCompanyPortfolioDTO.java
- outpolic/src/main/java/outpolic/user/main/controller/UserHomeController.java
- outpolic/src/main/java/outpolic/user/review/dto/UserReviewMainDTO.java
- outpolic/src/main/java/outpolic/user/review/mapper/UserReviewMainMapper.java
- outpolic/src/main/java/outpolic/user/review/service/UserReviewMainService.java
- outpolic/src/main/java/outpolic/user/review/service/impl/UserReviewMainServiceImpl.java
- outpolic/src/main/resources/mapper/user/company/UserCompanyMapper.xml
- outpolic/src/main/resources/mapper/user/review/UserReviewMainMapper.xml
- outpolic/src/main/resources/mapper/user/review/UserReviewMapper.xml
- outpolic/src/main/resources/templates/main.html
- outpolic/src/main/resources/templates/user/company/userCompanyProfileView.html
- outpolic/src/main/resources/templates/user/contents/userContentsView.html
- outpolic/src/main/resources/templates/user/search/userSearchView.html
detail : 유저메인(리뷰 및 박스 크기 정렬) 회사페이지 경로 매핑 및 이미지 경로 수정, 서치뷰 및 카테고리콘텐츠 뷰 박스크기 정렬
> [outpolic-KHB] 유저쪽 거의다 끝낸듯

- outpolic/src/main/java/outpolic/systems/config/WebConfig.java
- outpolic/src/main/java/outpolic/user/login/controller/UserLoginController.java
- outpolic/src/main/resources/mapper/user/login/UserLoginMapper.xml
- outpolic/src/main/resources/templates/admin/fragments/adminHeader.html
- outpolic/src/main/resources/templates/enter/fragments/enterHeader.html
- outpolic/src/main/resources/templates/enter/mypage/enterMypageView.html
- outpolic/src/main/resources/templates/user/fragments/userHeader.html
- outpolic/src/main/resources/templates/user/login/userLoginView.html
[상세 내용] 헤더에 user 프로필사진이 나오게 수정. 북마크 헤더 윗쪽 줄로 이동. 여러 분기처리 완료.
> [outpolic-SSY] 헤더 수정 및 분기점 정리

- outpolic/src/main/java/outpolic/enter/category/controller/EnterCategoryController.java
- outpolic/src/main/java/outpolic/enter/company/domain/EnterCompanyOutsourcingDTO.java
- outpolic/src/main/java/outpolic/enter/company/domain/EnterCompanyPortfolioDTO.java
- outpolic/src/main/java/outpolic/enter/contents/controller/EnterContentsController.java
- outpolic/src/main/java/outpolic/enter/main/controller/EnterHomeController.java
- outpolic/src/main/java/outpolic/enter/review/dto/EnterReviewMainDTO.java
- outpolic/src/main/java/outpolic/enter/review/mapper/EnterReviewMainMapper.java
- outpolic/src/main/java/outpolic/enter/review/service/EnterReviewMainService.java
- outpolic/src/main/java/outpolic/enter/review/service/impl/EnterReviewMainServiceImpl.java
- outpolic/src/main/java/outpolic/enter/search/controller/EnterSearchController.java
- outpolic/src/main/java/outpolic/enter/search/domain/EnterContentItemDTO.java
- outpolic/src/main/java/outpolic/enter/search/domain/EnterContentsDetailDTO.java
- outpolic/src/main/java/outpolic/enter/search/mapper/EnterSearchMapper.java
- outpolic/src/main/java/outpolic/enter/search/service/EnterSearchService.java
- outpolic/src/main/java/outpolic/enter/search/service/impl/EnterSearchServiceImpl.java
- outpolic/src/main/java/outpolic/user/search/domain/UserContentsDetailDTO.java
- outpolic/src/main/resources/mapper/enter/company/EnterCompanyMapper.xml
- outpolic/src/main/resources/mapper/enter/ranking/EnterRankingMapper.xml
- outpolic/src/main/resources/mapper/enter/review/enterReviewMainMapper.xml
- outpolic/src/main/resources/mapper/enter/search/EnterSearchMapper.xml
- outpolic/src/main/resources/templates/enter/company/enterCompanyProfileView.html
- outpolic/src/main/resources/templates/enter/contents/enterContentsView.html
- outpolic/src/main/resources/templates/enter/contentsParticular/enterContentsParticularView.html
- outpolic/src/main/resources/templates/enter/search/enterSearchView.html
- outpolic/src/main/resources/templates/enterMain.html
- outpolic/src/main/resources/templates/user/contentsParticular/userContentsParticularView.html
- outpolic/src/main/resources/templates/user/search/userSearchView.html
detail : 이제 할거 리뷰 기능 만들기 남았다 오늘 잠은 잘 수 있을까
> [outpolic-KHB] 유저에서 기능 추가 및 수정한거 전부 엔터로 옮김

- outpolic/src/main/java/outpolic/systems/config/WebConfig.java
- outpolic/src/main/java/outpolic/systems/interceptor/LoginUserBackInterceptor.java
- outpolic/src/main/java/outpolic/user/login/controller/UserLoginController.java
> [outpolic-SSY] 로그인 관련 인터셉터 정리중

- outpolic/src/main/resources/templates/admin/fragments/adminAside.html
- outpolic/src/main/resources/templates/admin/statistics/adminSearchStatisticsView.html
- outpolic/src/main/resources/templates/enter/search/enterSearchView.html
- outpolic/src/main/resources/templates/user/search/userSearchView.html
> [outpolic-KHB] 어드민페이지 태그빼버림

- outpolic/src/main/java/outpolic/systems/config/WebConfig.java
> [outpolic-KHB] 웹콘피그 수정

- outpolic/src/main/java/outpolic/admin/empowerment/controller/AdminEmpowermentController.java
- outpolic/src/main/java/outpolic/admin/empowerment/dto/AdminEmpowermentDTO.java
- outpolic/src/main/java/outpolic/admin/empowerment/mapper/AdminEmpowermentMapper.java
- outpolic/src/main/java/outpolic/admin/empowerment/service/AdminEmpowermentService.java
- outpolic/src/main/java/outpolic/admin/empowerment/service/Impl/adminEmpowermentServiceImpl.java
- outpolic/src/main/resources/mapper/admin/empowerment/AdminEmpowermentMapper.xml
- outpolic/src/main/resources/templates/admin/empowerment/adminEmpowermentView.html
- outpolic/src/main/resources/templates/admin/fragments/adminAside.html
> [outpolic-SSY] 관리자 권한 부여 쪽 뷰 생성

- outpolic/src/main/java/outpolic/user/inquiry/controller/UserInquiryController.java
- outpolic/src/main/java/outpolic/user/inquiry/domain/UserAnn.java
- outpolic/src/main/java/outpolic/user/inquiry/mapper/UserInquiryMapper.java
- outpolic/src/main/java/outpolic/user/inquiry/service/Impl/UserInquiryServiceImpl.java
- outpolic/src/main/java/outpolic/user/inquiry/service/UserInquiryService.java
- outpolic/src/main/resources/mapper/user/inquiry/UserAnnMapper.xml
- outpolic/src/main/resources/mapper/user/inquiry/UserInquiryMapper.xml
- outpolic/src/main/resources/static/user/assets/css/main.css
- outpolic/src/main/resources/templates/main.html
- outpolic/src/main/resources/templates/user/fragments/userPagination.html
- outpolic/src/main/resources/templates/user/inquiry/userInquiryFqaView.html
- outpolic/src/main/resources/templates/user/inquiry/userInquiryListView.html
- outpolic/src/main/resources/templates/user/inquiry/userInquiryTotalView.html
- outpolic/src/main/resources/templates/user/inquiry/userNoticeListView.html
> [outpolic-YSR] 유저 문의

- outpolic/src/main/java/outpolic/user/inquiry/mapper/UserInquiryMapper.java
- outpolic/src/main/java/outpolic/user/inquiry/service/Impl/UserInquiryServiceImpl.java
- outpolic/src/main/resources/templates/enter/fragments/enterPagination.html
- outpolic/src/main/resources/templates/enter/inquiry/enterInquiryListView.html
- outpolic/src/main/resources/templates/enter/inquiry/enterInquiryTotalView.html
- outpolic/src/main/resources/templates/enter/inquiry/enterNoticeListView.html
- outpolic/src/main/resources/templates/user/fragments/userPagination.html
- outpolic/src/main/resources/templates/user/inquiry/userInquiryListView.html
- outpolic/src/main/resources/templates/user/inquiry/userInquiryTotalView.html
- outpolic/src/main/resources/templates/user/inquiry/userNoticeListView.html
> [outpolic-YSR] user, enter 문의 찐빠 수정

- outpolic/src/main/java/outpolic/systems/config/WebConfig.java
- outpolic/src/main/java/outpolic/user/login/controller/UserLoginController.java
- outpolic/src/main/java/outpolic/user/mypage/controller/UserMypageController.java
- outpolic/src/main/resources/mapper/admin/empowerment/AdminEmpowermentMapper.xml
- outpolic/src/main/resources/templates/LimitInfo.html
- outpolic/src/main/resources/templates/error.html
- outpolic/src/main/resources/templates/user/fragments/userHeader.html
detail : 마이페이지에서 수정한 프로필사진이 바로 반영 안되는 오류 수정. 관리자가 usermain으로 이동시 오른쪽 상단에 관리자 페이지로 이동 버튼 노출되도록 추가.
> [outpolic-SSY] 에러랑 제재 알림 페이지 ui 수정 및 자잘한 ui 수정

- outpolic/src/main/java/outpolic/admin/inquiry/controller/AdminInquiryController.java
- outpolic/src/main/java/outpolic/admin/inquiry/mapper/AdminInquiryMapper.java
- outpolic/src/main/java/outpolic/admin/inquiry/service/AdminInquiryService.java
- outpolic/src/main/java/outpolic/admin/inquiry/service/Impl/AdminInquiryServiceImpl.java
- outpolic/src/main/java/outpolic/common/domain/PageInfo.java
- outpolic/src/main/resources/mapper/admin/inquiry/AdminInquiryMapper.xml
- outpolic/src/main/resources/templates/admin/fragments/adminAside.html
- outpolic/src/main/resources/templates/admin/fragments/adminPagination.html
- outpolic/src/main/resources/templates/admin/inquiry/adminInquiryView.html
> [outpolic-YSR] admin 사이드바 수정

- outpolic/src/main/java/outpolic/admin/declaration/controller/AdminDeclarationController.java
- outpolic/src/main/java/outpolic/admin/declaration/service/AdminDeclarationService.java
- outpolic/src/main/java/outpolic/admin/declaration/service/Impl/AdminDeclarationServiceImpl.java
- outpolic/src/main/java/outpolic/admin/limits/domain/AdminDeclarationFullInfo.java
- outpolic/src/main/java/outpolic/admin/limits/domain/AdminDeclarationLimits.java
- outpolic/src/main/java/outpolic/admin/limits/domain/AdminLimits.java
- outpolic/src/main/java/outpolic/admin/limits/domain/AdminLimitsReason.java
- outpolic/src/main/java/outpolic/admin/limits/mapper/AdminLimitsMapper.java
- outpolic/src/main/java/outpolic/admin/limits/service/AdminLimitsService.java
- outpolic/src/main/java/outpolic/admin/limits/service/Impl/AdminLimitsServiceImpl.java
- outpolic/src/main/resources/mapper/admin/declaration/AdminDeclarationMapper.xml
- outpolic/src/main/resources/mapper/admin/limits/AdminLimitsMapper.xml
> [outpolic-YSR] 제재 자동화 안돼.

- outpolic/src/main/java/outpolic/enter/mypage/controller/enterMypageController.java
- outpolic/src/main/java/outpolic/systems/config/WebConfig.java
- outpolic/src/main/java/outpolic/user/mypage/controller/UserMypageController.java
- outpolic/src/main/resources/templates/enter/fragments/enterProfile.html
- outpolic/src/main/resources/templates/user/fragments/userProfile.html
- outpolic/src/main/resources/templates/user/mypage/userMypageView.html
> [outpolic-SSY] 사진 저장 경로 수정

- outpolic/src/main/java/outpolic/admin/member/controller/adminMemberController.java
- outpolic/src/main/java/outpolic/admin/member/mapper/AdminMemberMapper.java
- outpolic/src/main/java/outpolic/admin/member/service/AdminMemberService.java
- outpolic/src/main/java/outpolic/admin/member/service/Impl/adminMemberServiceImpl.java
- outpolic/src/main/resources/mapper/admin/member/AdminMemberMapper.xml
- outpolic/src/main/resources/templates/admin/member/adminEnterListView.html
- outpolic/src/main/resources/templates/admin/member/adminMemberListView.html
- outpolic/src/main/resources/templates/enter/fragments/enterProfile.html
> [outpolic-SSY] admin 필터 정리중

- outpolic/src/main/java/outpolic/admin/loginHistory/controller/adminLoginHistoryController.java
- outpolic/src/main/java/outpolic/admin/loginHistory/dto/AdminLoginHistoryDTO.java
- outpolic/src/main/java/outpolic/admin/loginHistory/mapper/AdminLoginHistoryMapper.java
- outpolic/src/main/java/outpolic/admin/member/controller/adminEnterController.java
- outpolic/src/main/java/outpolic/admin/member/mapper/AdminEnterMapper.java
- outpolic/src/main/java/outpolic/admin/member/service/AdminEnterService.java
- outpolic/src/main/java/outpolic/admin/member/service/Impl/adminEnterServiceImpl.java
- outpolic/src/main/resources/mapper/admin/loginHistory/AdminEnterMapper.xml
- outpolic/src/main/resources/mapper/admin/member/AdminEnterMapper.xml
- outpolic/src/main/resources/templates/admin/fragments/adminAside.html
- outpolic/src/main/resources/templates/admin/loginHistory/adminLoginHistoryView.html
- outpolic/src/main/resources/templates/admin/member/adminEnterListView.html
- outpolic/src/main/resources/templates/admin/member/adminMemberListView.html
[상세 내용] admin 회원/기업목록에 총 몇건의 데이터가 있는지, 그리고 가입 일시 기준으로 정렬하는 기능 추가.
aside에 회원목록 기업목록 로그인기록 묶어서 회원 관리로 메뉴 정리
로그인 기록 페이지 추가. 지금은 더미데이터 넣어놨지만, 보고서 작성 후 실제 데이터로 매핑할 예정
> [outpolic-SSY] ADMIN 회원관리 필터 적용. 편의성 개선. ASIDE수정. 로그인 기록 페이지 추가

- outpolic/src/main/java/outpolic/systems/config/WebConfig.java
- outpolic/src/main/java/outpolic/user/withdrawn/controller/UserWithdrawnController.java
- outpolic/src/main/resources/mapper/admin/login/AdminLoginMapper.xml
- outpolic/src/main/resources/mapper/user/mypageEdit/UserMypageMapper.xml
> [outpolic-SSY] 짜잘한 오류수정

- outpolic/src/main/java/outpolic/enter/inquiry/controller/EnterInquiryController.java
- outpolic/src/main/java/outpolic/user/inquiry/controller/UserInquiryController.java
- outpolic/src/main/java/outpolic/user/inquiry/domain/UserAnn.java
- outpolic/src/main/java/outpolic/user/inquiry/mapper/UserInquiryMapper.java
- outpolic/src/main/java/outpolic/user/inquiry/service/Impl/UserInquiryServiceImpl.java
- outpolic/src/main/resources/mapper/user/inquiry/UserAnnMapper.xml
- outpolic/src/main/resources/templates/enter/fragments/enterPagination.html
- outpolic/src/main/resources/templates/enter/inquiry/enterInquiryListView.html
- outpolic/src/main/resources/templates/enter/inquiry/enterInquiryTotalView.html
- outpolic/src/main/resources/templates/enter/inquiry/enterNoticeListView.html
- outpolic/src/main/resources/templates/user/fragments/userPagination.html
- outpolic/src/main/resources/templates/user/inquiry/userInquiryListView.html
- outpolic/src/main/resources/templates/user/inquiry/userInquiryTotalView.html
- outpolic/src/main/resources/templates/user/inquiry/userNoticeListView.html
> [outpolic-YSR] 사용자 문의

- outpolic/src/main/java/outpolic/admin/login/controller/adminLoginController.java
- outpolic/src/main/java/outpolic/admin/loginHistory/mapper/AdminLoginHistoryMapper.java
- outpolic/src/main/java/outpolic/systems/util/IpUtils.java
- outpolic/src/main/java/outpolic/user/login/controller/UserLoginController.java
detail : 실제 ip 잡아오는 util 클래스 추가.
> [outpolic-SSY] ip 관련 기능 추가

- outpolic/src/main/java/outpolic/user/bookmark/dto/UserBookmarkViewDTO.java
- outpolic/src/main/java/outpolic/user/osst/controller/UserOsstController.java
- outpolic/src/main/java/outpolic/user/osst/mapper/UserOsstMapper.java
- outpolic/src/main/java/outpolic/user/review/dto/UserOutsourcingReviewDTO.java
- outpolic/src/main/java/outpolic/user/review/service/UserOutsourcingReviewService.java
- outpolic/src/main/java/outpolic/user/review/service/impl/UserOutsourcingReviewServiceImpl.java
- outpolic/src/main/resources/mapper/user/Osst/UserOsstMapper.xml
- outpolic/src/main/resources/mapper/user/bookmark/UserBookmarkMapper.xml
- outpolic/src/main/resources/mapper/user/review/UserReviewMapper.xml
- outpolic/src/main/resources/templates/user/bookmark/userBookmarkView.html
- outpolic/src/main/resources/templates/user/contents/userContentsView.html
- outpolic/src/main/resources/templates/user/osst/userOutsourcingStatusList.html
detail : 추후에 북마크 하트 색깔 칠하기 기능 구현하기
> [outpolic-KHB] 북마크 페이지 북마크 취소 기능 추가

- outpolic/src/main/java/outpolic/admin/limits/controller/AdminLimitsController.java
- outpolic/src/main/java/outpolic/admin/limits/domain/AdminLimits.java
- outpolic/src/main/java/outpolic/admin/limits/mapper/AdminLimitsMapper.java
- outpolic/src/main/java/outpolic/admin/limits/service/AdminLimitsService.java
- outpolic/src/main/java/outpolic/admin/limits/service/Impl/AdminLimitsServiceImpl.java
- outpolic/src/main/resources/mapper/admin/limits/AdminLimitsMapper.xml
- outpolic/src/main/resources/templates/admin/inquiry/adminInquiryView.html
- outpolic/src/main/resources/templates/admin/limits/adminLimitsAuthorityView.html
- outpolic/src/main/resources/templates/admin/limits/adminLimitsView.html
> [outpolic-YSR] 마지막 발악을 좀 해봤읍니다

- outpolic/src/main/java/outpolic/admin/limits/controller/AdminLimitsController.java
- outpolic/src/main/java/outpolic/admin/limits/mapper/AdminLimitsMapper.java
- outpolic/src/main/java/outpolic/admin/limits/service/AdminLimitsService.java
- outpolic/src/main/java/outpolic/admin/limits/service/Impl/AdminLimitsServiceImpl.java
- outpolic/src/main/resources/mapper/admin/limits/AdminLimitsMapper.xml
- outpolic/src/main/resources/templates/admin/limits/adminLimitsAuthorityView.html
- outpolic/src/main/resources/templates/admin/limits/adminLimitsResourcesView.html
> [outpolic-SSY] 회원 권한 페이지 필터 작업

- outpolic/src/main/java/outpolic/enter/goods/controller/EnterGoodsController.java
- outpolic/src/main/java/outpolic/enter/goods/dto/EnterGoodsDTO.java
- outpolic/src/main/java/outpolic/enter/goods/mapper/EnterGoodsMapper.java
- outpolic/src/main/java/outpolic/enter/goods/service/EnterGoodsService.java
- outpolic/src/main/java/outpolic/enter/goods/service/impl/EnterGoodsServiceImpl.java
- outpolic/src/main/resources/mapper/enter/goods/EnterGoodsMapper.xml
- outpolic/src/main/resources/templates/enter/goods/enterGoodsList.html
- outpolic/src/main/resources/templates/user/goods/userGoodsList.html
detail : 상품 결제 페이지(일반,기업)를 수정했습니다. 관리자가 상품을 등록, 상품 비활성을 할때 페이지에 노출되는 상품이 자동으로 변경 되도록 수정 했습니다. 하지만, 마일리지 유효성 검증은 아직 미구현입니다.
> [outpolic-LSJ] 상품 결제 페이지 수정

- outpolic/src/main/resources/templates/enter/goods/enterGoodsList.html
- outpolic/src/main/resources/templates/user/goods/userGoodsList.html
detail : 유효성 검증 처리를 추가했습니다. 마일리지는 최대 5000원까지 사용 가능. 보유 마일리지보다 많은 값을 입력할 수 없음.
> [outpolic-LSJ] 상품 결제 페이지 마일리지 기능

- outpolic/src/main/resources/templates/projectInfo.html
detail : 누가 table border 없앴을까요? 다시 넣어놨습니다.
> [outpolic-SSY] 프로젝트 인포 스타일 변경 및 내용 추가

- outpolic/src/main/java/outpolic/admin/empowerment/controller/AdminEmpowermentController.java
- outpolic/src/main/java/outpolic/admin/limits/controller/AdminLimitsController.java
- outpolic/src/main/java/outpolic/admin/login/controller/adminLoginController.java
- outpolic/src/main/java/outpolic/admin/login/dto/AdminLoginDTO.java
- outpolic/src/main/java/outpolic/admin/login/mapper/AdminLoginMapper.java
- outpolic/src/main/java/outpolic/admin/login/service/AdminLoginService.java
- outpolic/src/main/java/outpolic/admin/login/service/Impl/AdminLoginServiceImpl.java
- outpolic/src/main/java/outpolic/admin/loginHistory/controller/adminLoginHistoryController.java
- outpolic/src/main/java/outpolic/admin/member/controller/adminEnterController.java
- outpolic/src/main/java/outpolic/admin/member/controller/adminMemberController.java
- outpolic/src/main/resources/mapper/admin/login/AdminLoginMapper.xml
- outpolic/src/main/resources/templates/admin/empowerment/adminEmpowermentView.html
- outpolic/src/main/resources/templates/admin/login/alert.html
- outpolic/src/main/resources/templates/user/layout/userRegisterLayout.html
- outpolic/src/main/resources/templates/user/register/userRegisterView.html
detail : 다들 빠르게 각 페이지별로 무슨 권한 있어야 들어갈 수 있는지 주시길 바랍니다. 다 정리된 후 사진으로 공유해드리겠습니다. 각자 admin 2~5까지 부여해서 각자 본인 아이디로 접속해서 작업할 수 있도록 정리하겠슴.
> [outpolic-SSY] 관리자 권한에 따른 관리자 페이지 접근 제한거는중

- outpolic/src/main/java/outpolic/admin/declaration/controller/AdminDeclarationController.java
- outpolic/src/main/java/outpolic/admin/limits/controller/AdminLimitsController.java
- outpolic/src/main/java/outpolic/admin/limits/mapper/AdminLimitsMapper.java
- outpolic/src/main/java/outpolic/admin/limits/service/AdminLimitsService.java
- outpolic/src/main/java/outpolic/admin/limits/service/Impl/AdminLimitsServiceImpl.java
- outpolic/src/main/resources/mapper/admin/limits/AdminLimitsMapper.xml
- outpolic/src/main/resources/templates/admin/declaration/adminDeclarationResourcesView.html
- outpolic/src/main/resources/templates/admin/limits/adminLimitsResourcesView.html
> [outpolic-YSR] 필터 전체 완료

- outpolic/src/main/java/outpolic/admin/announcement/controller/AdminAnnController.java
- outpolic/src/main/java/outpolic/admin/announcement/domain/AdminAnn.java
- outpolic/src/main/java/outpolic/admin/announcement/mapper/AdminAnnMapper.java
- outpolic/src/main/java/outpolic/admin/announcement/service/AdminAnnService.java
- outpolic/src/main/java/outpolic/admin/announcement/service/Impl/AdminAnnServiceImpl.java
- outpolic/src/main/resources/mapper/admin/announcement/AdminAnnMapper.xml
- outpolic/src/main/resources/templates/admin/announcement/adminAnnView.html
- outpolic/src/main/resources/templates/admin/announcement/adminAnnWriteView.html
- outpolic/src/main/resources/templates/admin/fragments/adminAside.html
> [outpolic-YSR] 관리자 공지사항 작성

- outpolic/src/main/java/outpolic/admin/announcement/controller/AdminAnnController.java
- outpolic/src/main/java/outpolic/admin/declaration/controller/AdminDeclarationController.java
- outpolic/src/main/java/outpolic/admin/goods/controller/AdminGoodsController.java
- outpolic/src/main/java/outpolic/admin/inquiry/controller/AdminInquiryController.java
- outpolic/src/main/java/outpolic/admin/limits/controller/AdminLimitsController.java
- outpolic/src/main/java/outpolic/admin/osst/controller/AdminOsstController.java
- outpolic/src/main/java/outpolic/admin/outsourcing/controller/AdminOutsourcingController.java
- outpolic/src/main/java/outpolic/admin/points/controller/AdminPointsController.java
- outpolic/src/main/java/outpolic/admin/portfolio/controller/AdminPortfolioController.java
- outpolic/src/main/java/outpolic/admin/refund/controller/AdminRefundController.java
- outpolic/src/main/java/outpolic/admin/settlement/controller/AdminSettlementController.java
[상세 내용] 관리자 권한 설정하고 각각 페이지마다 권한 부여해서, 해당 권한 가지고있는 관리자만 페이지 조회해서 내역 확인 및 수정할 수 있게 함. 각자 얘기해준 관리자 번호 잘 기억해서 그거로 접속해주길 바라고 회원관리쪽은 왠만하면 들어가지 마시오.
> [OUTPOLIC-SSY] 관리자 권한 설정

- outpolic/src/main/java/outpolic/admin/announcement/controller/AdminAnnController.java
- outpolic/src/main/java/outpolic/admin/announcement/domain/AdminAnn.java
- outpolic/src/main/java/outpolic/admin/announcement/mapper/AdminAnnMapper.java
- outpolic/src/main/java/outpolic/admin/announcement/service/AdminAnnService.java
- outpolic/src/main/java/outpolic/admin/announcement/service/Impl/AdminAnnServiceImpl.java
- outpolic/src/main/resources/mapper/admin/announcement/AdminAnnMapper.xml
- outpolic/src/main/resources/static/admin/assets/css/adminInquiry.css
- outpolic/src/main/resources/static/admin/assets/css/main.css
- outpolic/src/main/resources/templates/admin/announcement/adminAnnView.html
- outpolic/src/main/resources/templates/admin/announcement/adminAnnWriteView.html
> [outpolic-YSR] 관리자 공지사항
